#+title: Anotação artigos 29.º a 32.º do Regulamento dos Serviços Digitais
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl chicago-fullnote-bibliography.csl

* Anotação artigo 29.º :ignore:
** Transcrição do artigo :ignore:

#+BEGIN_CENTER
Artigo 29.º \\
*Exclusão das micro e pequenas empresas*
#+END_CENTER

1. A presente secção não se aplica aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes que sejam consideradas micro ou pequenas empresas tal como definidas na Recomendação 2003/361/CE.

   A presente secção não se aplica aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes anteriormente qualificadas para o estatuto de pequena ou microempresa tal como definidas na Recomendação 2003/361/CE durante os 12 meses seguintes à perda desse estatuto nos termos do artigo 4.º, n.º 2, exceto quando se trate de plataformas em linha de muito grande dimensão, nos termos do artigo 33.º.

2. Em derrogação do n.º 1 do presente artigo, a presente secção aplica-se aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes que tenham sido designados como plataformas em linha de muito grande dimensão nos termos do artigo 33.º, independentemente de serem ou não consideradas micro ou pequenas empresas.

** Bibliografia :ignore:

[cite/nocite:@hofmann2023;@muller-terpitz2023;@wilman2024]

*Bibliografia:*

#+print_bibliography:


** Comentário
#+TOC: headlines 2 local

*** I - Antecedentes legislativos

O artigo 16.º da Proposta estabelecia que as disposições adicionais aplicáveis aos fornecedores de plataformas em linha não seriam aplicáveis aos fornecedores que fossem considerados micro ou pequenas empresas na aceção do anexo da Recomendação 2003/361/CE, excecção semelhante à que veio a ser consagrada neste preceito.

Comparando o artigo 16.º da Proposta e o artigo 29.º do RSD, este último introduz /(i)/ um período de transição de 12 meses nos casos em que o fornecedor de plataforma em linha perca o estatuto de micro ou pequena empresa e /(ii)/ um recorte da exclusão subjetiva esclarecendo que as disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes são sempre aplicáveis quando se trate de plataformas em linha de muito grande dimensão.

O recorte da exclusão subjetiva foi introduzido pelo Parlamento Europeu e pelo Conselho[fn:1]. O período de transição surge mais tarde no processo legislativo, na sequência de negociações interinstitucionais entre o Parlamento Europeu, o Conselho e a Comissão Europeia[fn:2]. No final do processo legislativo, dividiu-se a secção 3 da Proposta (que inicia no artigo 16.º) nas atuais secção 3, relativa às disposições adicionais aplicáveis aos fornecedores de plataformas em linha (artigos 19.º a 28.º do RSD) e secção 4, relativa às disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar
contratos à distância com comerciantes (artigos 29.º a 32.º do RSD). Tal motivou uma retificação da posição adotada em primeira leitura pelo Parlamento Europeu em 5 de julho de 2022, na qual se inseriu o atual artigo 29.º do RSD[fn:3].

*** II - Ponderação de interesses

O artigo 29.º é o resultado da procura de um equilíbrio entre dois interesses: a proteção dos consumidores e o apoio e desenvolvimento das micro, pequenas e médias empresas da União Europeia. Ambos se encontram consagrados no TFUE: a proteção dos consumidores nos artigos 12.º e 169.º e o apoio e desenvolvimentos das pequanas e médias empresas nos artigos 153.º, n.º 2, al. /b)/, e 173.º, n.º 1, 2.º travessão.

A isenção subjetiva a favor das micro e pequenas empresas visa evitar encargos desproporcionados[fn:4], pois as empresas de menor dimensão poderão não conseguir suportar os custos de /compliance/ com todas as obrigações definidas no RSD e acabariam prejudicadas por um instrumento que visa também proporcionar-lhes condições de concorrência equitativas[fn:5]. As micro e pequenas empresas beneficiam de outras isenções subjetivas nos artigos 15.º, n.º 2, e 19.º do RSD, prevendo-se no artigo 91.º, n.º 2, al. /d)/, do RSD a revisão destas isenções até 17 de novembro de 2027 e a partir daí quinquenalmente. Salienta-se que o legislador europeu entendeu que as obrigações estabelecidas pelo RSD não constituem encargos desproporcionados para as médias empresas e, em contraponto, estabeleceu obrigações específicas dos prestadores de mercados em linha relacionadas com a segurança dos produtos, sem consagrar qualquer exceção para as micro e pequenas empresas no Regulamento (UE) 2023/988 relativo à segurança geral dos produtos[fn:6].

*** III - Interpretação da norma
*1. Conceitos.* Os conceitos mais relevantes do artigo 29.º são, por um lado, os conceitos de "consumidor", "comerciante", "plataforma em linha", "contrato à distância" e "plataforma em linha de muito grande dimensão" definidos, respetivamente, nos artigos 3.º, e 33.º, n.ºs 1 e 4, para os quais se remete e, por outro, os conceitos de micro e pequena empresa, definidos na Recomendação 2003/361/CE[fn:7].

Estes conceitos efetuam o recorte subjetivo de quem está sujeito às disposições adicionais consagradas na secção IV do capítulo III e de quem beneficia da exclusão prevista no artigo 29.º. Assim, e por exemplo, o fornecedor de plataforma em linha que /ou/ não permita a celebração de contratos à distância /ou/ só permita a celebração de contratos à distância entre comerciantes não está obrigado a cumprir as disposições adicionais consagradas na secção IV do capítulo III. Por outro lado, o fornecedor de plataforma em linha que permita a celebração de contratos à distância com consumidores /e/ que seja considerado uma micro ou pequena empresa na aceção da Recomendação 2003/361/CE beneficia da exclusão consagrada no artigo 29.º, n.º 1, /exceto se/ a sua plataforma em linha for designada como uma plataforma de muito grande dimensão (artigo 29.º, n.º 2).

*2. Conceitos de micro e pequena empresa.* O conceito de empresa abrange "qualquer entidade que, independentemente da sua forma jurídica, exerce uma actividade econó-
mica."[fn:10] Uma micro empresa "é definida como uma empresa que emprega menos de 10 pessoas e cujo volume de negócios anual ou balanço total anual não excede 2 milhões de euros."[fn:8] Uma pequena empresa "é definida como uma empresa que emprega menos de 50 pessoas e cujo volume de negócios anual ou balanço total anual não excede 10 milhões de euros."[fn:9] Atende-se também às relações entre empresas para efeitos de apuramento destes critérios, classificando as empresas como autónomas, parceiras ou associadas[fn:11] e esclarecendo que uma empresa não pode ser considerada uma pequena ou média empresa "se 25% ou mais do seu capital ou dos seus direitos de voto forem controlados, directa ou indirectamente, por uma ou várias colectividades públicas ou organismos públicos, a título individual ou conjuntamente."[fn:12] A Recomendação estabelece ainda os dados a considerar para cálculo dos efetivos e dos montantes financeiros[fn:13].

De acordo com o TJUE, o conceito de micro, pequenas e médias empresas (PME) da Recomendação 2003/361/CE deve ser objeto de interpretação estrita, pois as vantagens concedidas às PME constituem, muitas vezes, exceções às regras gerais[fn:14][cite:@hofmann2023;art. 29.º, n.º 7, defendem que a interpretação não deve ser estrita, mas sim tendo em conta a sua função específica].

*3. Não aplicabilidade das disposições da presente secção*. Beneficiam da não aplicabilidade desta secção todos os fornecedores de plataformas em linha que permitam a celebração de contratos à distância com consumidores que sejam, na aceção da Recomendação 2003/361/CE, uma micro ou uma pequena empresa (artigo 29.º, n.º 1, 1.º parágrafo do RSD). Como a exclusão abrange as micro e as pequenas empresas, bastará cumprir os critérios definidos na recomendação para estas últimas para beneficiar da exclusão.[cite:Cf., no mesmo sentido, @hofmann2023; art. 29.º, n.º 10]

Sendo a exclusão um benefício concedido aos os fornecedores de plataformas em linha que permitam a celebração de contratos à distância com consumidores que sejam, na aceção da Recomendação 2003/361/CE, uma micro ou uma pequena empresa, nada impede que estes voluntariamente cumpram uma ou mais das obrigações previstas nesta secção[cite:Cf., considerando n.º 57 do RSD e @muller-terpitz2023; art. 29.º, n.º 6].

*4. Perda de estatuto de micro ou pequena empresa*. Caso o fornecedor deixe de preencher os critérios para ser considerado, pelo menos, uma pequena empresa na aceção da Recomendação 2003/361/CE, ele beneficia de um período de 12 meses contados a partir da data em que perdeu o estatuto de micro ou pequena empresa (artigo 29.º, n.º 1, 2.º parágrafo). Uma empresa perde o estatuto de micro ou pequena empresa se, numa base anual, superar o limiar de efetivos e ou os limiares financeiros /e/ se tal se repetir durante dois exercícios consecutivos[fn:15]. Perdido o estatuto de micro ou pequena empresa, o fornecedor só terá a obrigação de cumprir com as normas da presente secção passados 12 meses. Este período de transição compreende-se como força de mitigar os encargos inerentes ao cumprimento das obrigações desta secção.

*5. Fornecedores de plataformas em linha de muito grande dimensão*. Os fornecedores de plataformas em linha que permitam a celebração de contratos à distância que tenham sido designadas como plataformas em linha de muito grande dimensão (cf. artigo 33.º e ss.) não beneficiam da exclusão (artigo 29.º, n.º 2, do RSD) nem do período de transição em caso de perda do estatuto de micro ou pequena empresa (artigo 29.º, n.º 1, 2.º parágrafo, /in fine/, do RSD). Embora improvável, é possível que uma micro ou pequena empresa seja a fornecedora de uma plataforma de muito grande dimensão, pois os critérios de determinação das micro e pequenas empresas são distintos dos da determinação das plataformas em linha de muito grande dimensão[cite:@wilman2024; art. 29, n.º 5]. Considerando o maior alcance e impacto das plataformas em linha de muito grande dimensão (que têm um número médio mensal de destinatários activos do serviços na União Europeia igual ou superior a 45 milhões), o legislador considerou que o valor da proteção dos consumidores deve prevalecer sobre o apoio às micro e pequenas empresas, razão pela qual mesmo que o fornecedor da plataforma em linha de muito grande dimensão seja uma micro ou pequena empresa, na aceção da Recomendação 2003/361/CE, ele encontra-se obrigado ao cumprimento das disposições da presente secção.

Caso o fornecedor seja uma micro ou pequena empresa, na aceção da Recomendação 2003/361/CE, e a sua plataforma em linha que permite a celebração de contratos à distância seja designada pela Comissão Europeia como uma plataforma em linha de muito grande dimensão pode questionar-se a partir de que data devem ser cumpridas as disposições previstas nos artigos 30.º a 32.º do RSD. Resulta do artigo 33.º, n.º 6, 2.º parágrafo, do RSD que as obrigações adicionais dos fornecedores de plataformas em linha de muito grande dimensão e de motores de pesquisa em linha de muito grande dimensão no que se refere à gestão de riscos sistémicos (secção 5 do capítulo III) são aplicáveis no prazo de quatro meses após a notificação da designação ao fornecedor. Nada se prevê, porém, quanto à data em que são aplicáveis as disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes (secção 4 do capítulo III). Parecem possíveis duas interpretações: a primeira, mais literal, é a de que as disposições da presente secção são aplicáveis a partir da data da notificação ao fornecedor da designação da sua plataforma como uma plataforma em linha de muito grande dimensão; a segunda é a de que as disposições da presente secção são aplicáveis 4 meses após a notificação ao fornecedor da designação da plataforma como plataforma em linha de muito grande dimensão, aplicando analogicamente o prazo previsto no artigo 33.º, n.º 6, 2.º parágrafo do RSD. Esta segunda opção é mais consentânea com a ponderação de interesses acima referida. Considerando o teor das obrigações previstas nos artigos 30.º a 32.º do RSD, a caracterização do fornecedor como micro ou pequena empresa na aceção da Recomendação 2003/361/CE e a classificação como plataforma em linha de muito grande dimensão depender de uma decisão da Comissão Europeia, parece adequado o prazo de quatro meses para o fornecedor assegurar o cumprimento das obrigações previstas na presente secção.

* Anotação artigo 30.º :ignore:
** Transcrição do artigo :ignore:
#+BEGIN_CENTER
Artigo 30.º \\
*Rastreabilidade dos comerciantes*
#+END_CENTER

1.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes asseguram que os comerciantes só possam utilizar essas plataformas em linha para promover mensagens ou oferecer produtos ou serviços aos consumidores localizados na União se, antes da utilização dos seus serviços para estes fins, tiverem obtido as seguintes informações, sempre que forem aplicáveis ao comerciante:
   a) O nome, endereço postal, número de telefone e endereço de correio eletrónico do comerciante;
   b) Uma cópia do documento de identificação do comerciante ou qualquer outra identificação eletrónica, tal como definida no artigo 3.º do Regulamento (UE) n.º 910/2014 do Parlamento Europeu e do Conselho (40);
   c) Os dados da conta de pagamento do comerciante;
   d) Se o comerciante estiver inscrito num registo comercial ou noutro registo público equivalente, o registo comercial em que se encontra inscrito e o respetivo número de registo, ou forma de identificação equivalente nesse registo;
   e) Uma autocertificação do comerciante, em que se compromete a oferecer apenas produtos ou serviços que respeitem as regras aplicáveis do direito da União.
2.   Ao receber as informações a que se refere o n.º 1, e antes de permitir que o comerciante em causa utilize os seus serviços, o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes deve, seja através da utilização de uma base de dados oficial em linha ou interface em linha de acesso livre, disponibilizada por um Estado-Membro ou pela União, seja através da apresentação de pedidos ao comerciante para fornecer documentos comprovativos provenientes de fontes fiáveis, envidar todos os esforços para avaliar se as informações referidas no n.º 1, alíneas a) a e), são fiáveis e completas. Para efeitos do presente regulamento, os comerciantes são responsáveis pela exatidão das informações prestadas.

   No que diz respeito aos comerciantes que já utilizam os serviços de fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes para os fins referidos no n.º 1 em 17 de fevereiro de 2024, os fornecedores envidam todos os esforços para obter dos comerciantes em causa as informações referidas na lista no prazo de 12 meses. Se os comerciantes em causa não fornecerem as informações dentro deste prazo, os fornecedores suspendem o fornecimento dos seus serviços a tais comerciantes até que estes tenham fornecido todas as informações.
3.   Se o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes obtiver indicações suficientes de que qualquer informação a que se refere o n.º 1 obtida do comerciante em causa é inexata, está incompleta ou não está atualizada, ou se tiver motivos para o supor, esse fornecedor solicita ao comerciante que corrija a situação, sem demora ou no prazo fixado pelo direito da União e nacional.

   Se o comerciante não corrigir ou completar essas informações, o prestador de plataformas em linha que permite aos consumidores celebrar contratos à distância com comerciantes suspende rapidamente a prestação do seu serviço a esse comerciante em relação à oferta de produtos ou de serviços aos consumidores localizados na União até que o pedido tenha sido plenamente satisfeito.
4.   Sem prejuízo do disposto no artigo 4.º do Regulamento (UE) 2019/1150, caso um fornecedor de uma plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes se recuse a autorizar um comerciante a utilizar o seu serviço nos termos do n.º 1 do presente artigo, ou suspenda a sua prestação nos termos do n.º 3 do presente artigo, o comerciante em causa tem o direito de apresentar uma reclamação nos termos dos artigos 20.º e 21.º do presente regulamento.
5.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes armazenam as informações obtidas nos termos dos n.ºs 1 e 2 de forma segura durante um período de seis meses após a cessação da relação contratual com o comerciante em causa. Posteriormente, apagam as informações.
6.   Sem prejuízo do disposto no n.º 2 do presente artigo, o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes só divulga as informações a terceiros quando tal lhe for exigido nos termos do direito aplicável, incluindo as decisões a que se refere o artigo 10.º e quaisquer decisões emitidas pelas autoridades competentes dos Estados-Membros ou pela Comissão para o desempenho das suas funções nos termos do presente regulamento.
7.   O fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes disponibiliza as informações a que se refere o n.º 1, alíneas a), d) e e), na sua plataforma em linha aos destinatários do serviço de forma clara, facilmente acessível e compreensível. Essas informações ficam disponíveis pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas.

** Bibliografia :ignore:
** Comentário
*** I - Antecedentes legislativos
A Proposta, no seu artigo 22.º, previa um regime de rastreabilidade dos comerciantes, o qual parece ter surgigo como resposta à crítica ao modo como foi aplicado o artigo 5.º da DCE[fn:16]. No decurso do processo legislativo, o artigo 22.º da Proposta foi objeto de alterações, destacando-se o aditamento de uma disposição transitória (n.º 2, 2.º parágrafo), o ajustamento do dever de verificar as informações recebidas a cargo do fornecedor, precisando que este não é responsável pela exatidão das informações (n.º 2, 1.º parágrafo), o alargamento do prazo de conservação dos dados (n.º 5) e o desenvolvimento do número relativo à conceção e organização da plataforma em linha e a sua autonomização naquele que é atualmente o artigo 31.º do RSD.

*** II - Teleologia da norma
O objetivo desta norma é "(...) contribuir para um ambiente em linha seguro, fiável e transparente para os consumidores, bem como para outras partes interessadas, como comerciantes concorrentes e titulares de direitos de propriedade intelectual (...)"[fn:17]. A norma opera com base no princípio /Know Your Business Customer/[cite:Cf., neste sentido, @wilman2024 art. 30.º, n.º 2;@hofmann2023 art. 30.º, nº 1;@muller-terpitz2023 art. 30.º, n.º 2]. Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes devem recolher e disponibilizar informação sobre os comerciantes, antes de os autorizarem a dirigirem, através da plataforma em linha, a sua atividade aos consumidores localizados na União Europeia. A informação recolhida permitirá rastrear os comerciantes, promovendo a transparência e melhorando a proteção dos consumidores e de outras partes interessadas. Espera-se também que dissuada os comerciantes de venderem produtos ou serviços em violação das regras aplicáveis[fn:18].

*** III - Âmbito de aplicação
*1. Âmbito de aplicação subjetivo*. O artigo 30.º é aplicável aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes que não beneficiem da isenção prevista no artigo 29.º. Na concretização dos destinatários da norma são relevantes os conceitos de "consumidor", "comerciante", "plataforma em linha", e "contrato à distância" definidos no artigo 3.º, e para o qual se remete. O conceito de "plataformas em linha que permitem aos consumidores celebrar contratos à distância" é muito próximo do conceito de "mercado em linha"[fn:19], mas não inclui as plataformas que apenas permitem a celebração de contratos entre consumidores[cite:@wilman2024 p. 224, n.º 8;@hofmann2023 art. 30.º, n.º 8]. Assinala-se que apesar de o conceito de "comerciante" se encontrar definido no artigo 3.º, o considerando n.º 72 indica que "(...) qualquer comerciante, independentemente de ser uma pessoa singular ou coletiva, identificado como tal com base no artigo 6.º-A, n.º 1, alínea /b)/, da Diretiva 2011/83/UE e no artigo 7.º, n.º 4, alínea /f)/, da Diretiva 2005/29/CE, deverá ser rastreável quando oferece um produto ou serviço através de uma plataforma em linha."

*2. Âmbito de aplicação espacial*. A obrigação imposta neste artigo aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes está limitada em função do âmbito de aplicação espacial do RSD, definido no art. 2.º, para o qual se remete. Deste modo, se o comerciante não prestar as informações mencionados no n.º 1 ou se não as corrigir ou atualizar dentro do prazo fixado no n.º 3, o fornecedor da plataforma tem o dever de, respetivamente, (i) não autorizar ou (ii) suspender a utilização da plataforma pelo comerciante para promover mensagens ou oferecer produtos ou serviços /apenas aos consumidores localizados na União Europeia/. Tal significa que nestes casos o fornecedor cumpre o artigo 30.º se recusar a autorização ou suspender a utilização da sua plataforma pelo comerciante apenas aos consumidores localizados na União Europeia, por exemplo, através do mecanismo de bloqueio geogrático, permitindo que o comerciante continue a usar a plataforma para dirigir a sua atividade aos consumidores localizados fora da União Europeia[cite:Cf., no mesmo sentido, @hofmann2023;art. 30.º, n.º 12].

*3. Âmbito de aplicação material*. A ratreabilidade dos comerciantes tem por objeto a utilização das plataformas em linha "promover mensagens e "oferecer produtos ou serviços". A promoção de mensagens pelo comerciante parece reconduzível ao conceito de "anúncio publicitário" definido no artigo 3.º, al. /r)/. As noções de "produtos" e "serviços" parecem ser, respetivamente, as definidas no art. 2.º, n.º 5, da Diretiva relativa a certos aspetos dos contratos de compra e venda de bens[fn:20] e no art. 4.º, n.º 1, da Diretiva serviços[fn:21]. O artigo, ao mencionar a promoção de mensagens e a oferta de produtos e serviços, /não/ abrange a conclusão do contrato[cite:Cf., neste sentido;@hofmann2023 art. 30.º, n.º 12;@muller-terpitz2023 art. 30.º, n.º 6].

*** IV - Recolha de informações (n.º 1)
*4. Obrigação de recolha e ónus de prestação de informação*. Resulta do n.º 1 que os fornecedores das plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes têm a obrigação de não permitir a utilização da sua plataforma pelo comerciante para promover mensagens ou oferecer produtos e serviços aos consumidores localizados na União Europeia /antes/ de recolhida a informação elecanda neste número.

Do n.º 1 não parece resultar um dever, mas sim ónus do comerciante prestar a informação. Dito de outra forma, o comerciante não se encontra obrigado pelo artigo 30.º a prestar a informação ao fornecedor da plataforma em linha, mas se não o fizer não poderá utilizar a plataforma para promover mensagens ou oferecer produtos ou serviços aos consumidores localizados na União Europeia[cite:@hofmann2023;art. 30.º, n.º 12]. O artigo não impede que o fornecedor permita que o comerciante: /(i)/ utilize a plataforma em linha em momento anterior ao da prestação da informação para realizar atos diferentes da promoção de mensagens ou oferta de produtos ou serviços, como, por exemplo, a organização da sua "loja virtual" na plataforma em linha[cite:@hofmann2023;art. 30.º, n.º 11]; /(ii)/ dirija a sua atividade para os consumidores localizados fora da União Europeia (cf. /supra/ *III.2.*).

*a) Nome, endereço postal, número de telefone e endereço de correio eletrónico do comerciante*. Esta informação já é exigida no artigo 6.º da Diretiva relativa aos direitos dos consumidores[fn:22] e visa facilitar a identificação e contacto com o comerciante e promover um ambiente em linha mais seguro, em primeira linha para os consumidores. Neste contexto, o comerciante (seja ele pessoa singular ou coletiva) deve indicar o seu nome completo. O endereço postal deve corresponder à morada onde o comerciante pode ser judicialmente demandado (podendo, consoante os casos, ser uma das que resulta da aplicação dos artigos 4.º, 7.º, n.º 5, ou 17.º, n.º 2, conjugados com o artigo 63.º, todos do Regulamento Bruxelas I /bis/[fn:23]). A indicação de um número telefone é obrigatória, divergindo do que decidiu o TJUE no contexto da Diretiva relativa aos direitos dos consumidores[fn:24]. Por fim, o endereço de correio eletrónico indicado deve permitir o efetivo contacto com o comerciante e não pode ser um endereço configurado com respostas automáticas que remetam para outros meios de contacto[cite:@hofmann2023;art. 30.º, n.º 19].

*b) Cópia do documento de identificação do comerciante ou qualquer outra identificação eletrónica*. O fornecedor deve receber cópia do documento de identificação do comerciante. No caso de comerciantes com cartão do cidadão português, a cópia pode ser substituída pelo documento pdf gerado pela aplicação móvel gov.pt, ao abrigo do Regulamento eIDAS[fn:25].

*c) Dados da conta de pagamento do comerciante*. O fornecedor deve receber informações sobre a conta de pagamento do comerciante. A noção de "conta de pagamento" não está definida no RSD, mas corresponde à definição constante do artigo 2.º, n.º 22[fn:26], do Regulamento relativo às taxas de intercâmbio aplicáveis a operações de pagamento baseadas em cartões[fn:27].

*d) Registo comercial ou outro registo público equivalente*. Caso o comerciante esteja inscrito no registo comercial ou em outro registo público equivalente, o fornecer deve receber a informação de que o comerciante se encontra inscrito e o seu número de registo.

*e) Autocertificação do comerciante*. O fornecedor deve receber uma autocertificação do comerciante em que este se compromete a oferecer apenas produtos ou serviços que respeitem as regras aplicáveis do direito da União. Esta autocertificação tem um carácter geral[cite:@wilman2024;art. 30.º, n.º 7]. É dúvidoso que esta autocertificação seja eficaz na promoção de um ambiente em linha mais seguro ou seja um dissuasor para os comerciantes que pretendam dirigir a sua atividade para o mercado da União Europeia sem cumprir as regras que aí são aplicáveis[cite:Suscitando dúvidas similares, cf. @hofmann2023 art. 30.º, n.º 23;@muller-terpitz2023 art. 30.º, n.º 14].

*** V - Disposição transitória (n.º 2, 2.º parágrafo)
A recolha de informação prevista no n.º 1 deste artigo parte do pressuposto de que o comerciante ainda não utiliza a plataforma em linha do fornecedor. Se o comerciante, à data da entrada em aplicação das normas do RSD, já utilizava a plataforma em linha, o fornecedor deve solicitar-lhe a prestação das informações elencadas no n.º 1. Se os comerciantes em causa não fornecerem as informações até 17 de fevereiro de 2025, os fornecedores suspendem o fornecimento dos seus serviços a tais comerciantes até que estes tenham fornecido todas as informações.

*** VI - Obrigação de avaliação prévia da informação obtida (n.º 2, 1.º parágrafo)
*5. Regime*. Recebidas as informações elencadas no n.º 1, o fornecedor deve envidar todos os esforços para avaliar se as informações recebidas são fiáveis e completas antes de permitir a utilização da sua plataforma pelo comerciante para propor mensagens e oferecer produtos ou serviços aos consumidores localizados na União Europeia. Esta obrigação de avaliação prévia da informação obtida é uma novidade.

*6. Objeto da avaliação*. O fornecedor deve avaliar se as informações são fiáveis e completas. Verificar se as informações estão ou não completas não parece suscitar dificuldades de maior[cite:@wilman2024; art. 30.º, n.º 15]. Para avaliar a fiabilidade das informações sugere-se a utilização de "bases de dados oficiais em linha e interfaces em linha de livre acesso, como registos comerciais nacionais e o Sistema de Intercâmbio de Informações sobre o IVA, ou solicitar aos comerciantes em causa que forneçam documentos comprovativos fiáveis, como cópias de documentos de identidade, extratos certificados de contas de pagamento, certificados de empresa e certidões de registo comercial", admitindo-se ainda o recurso "a outras fontes, disponíveis para utilização à distância, que proporcionem um grau de
fiabilidade semelhante para efeitos de cumprimento desta obrigação"[fn:28]. A verificação da fiabilidade da autocertificação parece problemática, uma vez que incide sobre comportamentos futuros[cite:@wilman2024; art. 30.º, n.º 16].

O fornecedor não é obrigado a verificar a exatidão das informações recebidas. O responsável pela exatidão das informações é o comerciante (art. 30.º, n.º 2, 1.º parágrafo, /in fine/ do RSD). Se, no entanto, o fornecedor tiver conhecimento de que as informações são inexatas, não deve autorizar a utilização da plataforma antes da correção das mesmas pelo comerciante[cite:Cf., neste sentido, @hofmann2023;art. 30.º, n.º 29].

*7. Critério de diligência*. Estabelece-se que o fornecedor deve "envidar todos os esforços" para avaliar se as informações são fiáveis e completas. Esta expressão deve ser interpretada com cautela e compaginada com o esclarecimento no considerando n.º 73 de que "os fornecedores de plataformas em linha em causa não deverão ser obrigados a realizar exercícios de apuramento de factos em linha excessivos ou dispendiosos, nem a efetuar verificações desproporcionadas no local". Considera-se que o critério de diligência a adotar é o de "melhores esforços"[cite:@wilman2024 art. 30.º, n.º 13;@hofmann2023 art. 30.º, n.º 25;@muller-terpitz2023 art. 30.º, n.º 18], correspondente à versão em língua inglesa /"best efforts"/ e também ao artigo 17.º, n.º 4, da DMD. O conceito de "melhores esforços" não se encontra definido no RSD e deve ser objeto de interpretação autónoma, a qual deve atender à finalidade e objetivos do artigo 31.º e do RSD. Ainda assim, pensa-se que é possível traçar paralelos com a utilização do conceito no artigo 17.º, n.º 4, da DMD e tomar em consideração as orientações da Comissão Europeia sobre este conceito nessa sede[fn:31]. Não se visa garantir um determinado resultado, o que compreende em face do art. 8.º do RSD e da vontade de não impor encargos desproporcionados[fn:30]. Deve ser feita uma análise casuística, atendendo às cirscunstâncias do caso concreto e à complexidade da avaliação, sempre tendo em atenção o princípio da proporcionalidade. Pode questionar-se se o fornecedor empregou os seus "melhores esforços" se efetuou a sua avaliação com base num (e apenas um) dos elementos elencados no art. 2.º, n.º 2[cite:@hofmann2023; art. 30.º, n.º 26]. Atendendo à natureza casuística do conceito, a resposta afirmativa ou negativa a esta questão dependerá das circunstâncias do caso concreto.

*** VII - Informações inexatas, incompletas ou desatualizadas (n.º 3)

*8. Regime*. Se o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes obtiver indicações suficientes ou motivos para supor que qualquer informação a que se refere o n.º 1 obtida do comerciante em causa é inexata, incompleta ou está desatualizada, o fornecedor deve solicitar ao comerciante que corrija a situação, sem demora ou no prazo fixado pelo direito da União e nacional.

*9. Tipologia de informações*. O n.º 3 refere informações inexatas, incompletas ou desatualizadas. São informações inexatas aquelas que não correspondem à realidade (/v.g./: o comerciante indica um número de telefone que não lhe pertence). São informações incompletas aquelas em que não consta a totalidade da informação necessária (/v.g./: o comerciante indica a a rua, cidade e país da sua sede, mas não indica o n.º da porta). Uma informação desatualizada é uma informação que era exata e completa quando foi prestada, mas com o decurso de tempo se tornou inexata (/v.g./: o comerciante indicou a morada da sede, mas, posteriormente, transferiu a sede para outro local). Na verdade, crê-se que as informações desatualizadas serão sempre informações inexatas e, por isso, duvida-se que as mesmas tenham autonomia face a estas últimas[cite:@muller-terpitz2023; art. 30.º, n.º 31].

*10. Indicações suficientes ou motivos para supor*. O dever do fornecedor de solicitar a correção ao comerciante surge quando obtiver indicações suficientes ou motivos para supor que as informações prestadas são inexatas, incompletas ou desatualizadas. O conceito de indicações suficientes não é definido no RSD. Pensa-se que será uma indicação suficiente, por exemplo, uma comunicação de um consumidor a informar, por exemplo, que o endereço de correio eletrónico disponibilizado pelo comerciante não permite o contacto. Quanto aos motivos para supor, considera-se que eles permitem ao fornecedor efetuar uma verificação oficiosa da correção, completude e atualidade das informações prestadas pelo comercianteo[cite:@hofmann2023 art. 30.º, n.ºs 36 e 37;@muller-terpitz2023 art. 30.º, n.º 28].

*11. Correção das informações*. O fornecedor deve solicitar ao comerciante que corrija a situação, sem demora ou no prazo fixado pelo direito da União e nacional. Visa-se uma correção sem atrasos indevidos. Não parece possível fixar o prazo de forma rígida, uma vez que o mesmo deverá atender às circunstâncias do caso concreto, nomeadamente à dificuldade de efetuar a correção[cite:@hofmann2023; art. 30.º, n.º 42].

*12. Consequência jurídica*. Efetuada a solicitação de correção das informações, o comerciante pode /(i)/ corrigir as informações dentro do prazo fixado, /(ii)/ corrigir as informações fora do prazo ou /(iii)/ pode não corrigir as informações. No primeiro caso, o fornecedor deve manter o serviço e pode, ao abrigo do n.º 3, examinar as informações corrigidas para apurar se há novas informações inexatas, incompletas ou desatualizadas. Nos segundo e terceiro casos, o fornecedor deve suspender rapidamente o serviço que presta ao comerciante, mas apenas quanto aos consumidores localizados na União Europeia (o que pode ser feito recorrendo ao mecanismo de bloqueio geográfico). A diferença entre o segundo e terceiro casos, encontra-se na possibilidade de o comerciante vir a efetuar, tardiamente, a correção das informações. Nesse caso é sustentado que o fornecedor deve examinar a informação antes de levantar a suspensão[cite:@hofmann2023; art. 30.º, n.º 44].

*** VIII - Direito de apresentar uma reclamação (n.º 4)

Nos casos em que um fornecedor de uma plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes se recuse a autorizar um comerciante a utilizar o seu serviço ao abrigo do n.º 1 ou suspenda a utilização do seu serviço ao abrigo do n.º 3, o comerciante tem o direito de apresentar uma reclamação nos termos dos artigos 20.º e 21.º do presente regulamento, em acréscimo ao direito previsto no artigo 4.º, n.º 3, do Regulamento P2B[fn:32].

*** IX - Conservação dos dados (n.º 5)
O fornecedor de plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes está obrigado a armazenar as informações que obtenha ao abrigo dos n.ºs 1 e 2 de forma segura até que decorram 6 meses contados do termo da relação contratual com o comerciante. A Proposta previa a conservação apenas até ao termo da relação contratual[fn:34]. O alargamento do prazo de conservação constitui um reforço da proteção dos consumidores e pode ser necessário no contexto do art. 32.º[cite:@hofmann2023; art. 30.º, n.º 48]. Durante esse período os dados devem conservados de forma segura, isto é utilizando meios tecnológicos adequados para garantir a segurança dos dados recebidos, atendendo também à natureza destes[cite:@muller-terpitz2023; art. 30.º, n.º 38]. Findo o prazo de conservação, o fornecedor deve apagar os dados, salvo se estiver sujeito a outras eventuais "obrigações de conservar determinados conteúdos durante períodosde tempo mais longos previstas no direito da União ou direito nacional que seja conforme com direito da União"[fn:35].

Esta obrigação de tratamento de dados visa "permitir que sejam apresentadas reclamações contra o comerciante ou que sejam cumpridas as decisões relacionadas com o comerciante" e é considerada pelo legislador europeu "necessária e proporcionada para que as informações possam ser acedidas, nos termos da legislação aplicável, nomeadamente em matéria de proteção de dados pessoais, por autoridades públicas e entidades privadas com um interesse legítimo, incluindo através das decisões de prestação de informações referidas no presente regulamento"[fn:33].

*** X - Divulgação das informações (n.ºs 6 e 7)
*13. Considerações gerais*. Os n.ºs 6 e 7 regulam a divulgação das informações obtidas ao abrigo dos n.ºs 1 e 2 pelo fornecedor. O n.º 6 regula a divulgação das informações a terceiros. O n.º 7 obriga o fornecedor a publicar, pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas, as informações obtidas ao abrigo do n.º 1, alíneas /a)/, /d)/ e /e)/ (cf. /supra/ *IV.4.a), d)* e *e)*). Deste modo, e como regra geral, a informação obtida ao abrigo do n.º 1, alíneas /a)/, /d)/ e /e)/, ficará disponível ao público em geral, pois as plataformas em linha que permitem a celebração de aos consumidores celebrar contratos à distância com consumidores não limitam a visualização de informações sobre produtos e serviços na sua plataforma em linha aos cibernautas que criaram uma conta na plataforma e acederam à mesma antes de navegarem pela plataforma. Deste modo, o n.º 6 releva, primordialmente, para conseguir o acesso às informações sobre os dados de identificação (n.º 1, alínea /b)/) e os dados da conta de pagamento (n.º 1, alínea /c)/) do comerciante.

*14. Divulgação das informações a terceiros (n.º 6)*. O fornecedor só pode divulgar as informações obtidas ao abrigo do n.º 1 e 2 a terceiros quando tal lhe seja exigido nos termos do Direito aplicável. O n.º 6 enuncia, sem limitar, que o fornecedor deve divulgar as informações quando tal lhe seja exigido no contexto de uma decisão do artigo 10.º do RSD ou de quaisquer decisões emitidas pelas autoridades competentes dos Estados-Membros ou pela Comissão para o desempenho das suas funções nos termos do presente regulamento.

*15. Divulgação na plataforma das informações previstas no n.º 1, alíneas /a)/, /d)/ e /e)/* (n.º 7). As informações relativas ao nome, endereço postal, número de telefone e endereço de correio eletrónico do comerciante (n.º 1, alínea /a)/), ao registo comercial ou outro registo público equivalente, se o comerciante estiver inscrito (n.º 1, alínea /b)/) e à autocertificação (n.º 1, alínea /e)/) devem ser disponibilizadas aos destinatários de forma clara, facilmente acessível e compreensível e pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas.

*a) Divulgação de forma clara, facilmente acessível e compreensível*. A divulgação das informações deve ser efetuada de forma clara, facilmente acessível e compreensível. A informação é divulgada de forma clara se for facilmente identificável, procurando evitar-se ambiguidades e dúvidas interpretativas[cite:@muller-terpitz2023; art. 30.º, n.º 43]. A informação é divulgada de forma facilmente acessível se o destinatário do serviço consegue aceder à informação sem necessitar de pesquisar muito por ela[cite:@hofmann2023;art. 30.º, n.º 51]. Por fim, a informação é divulgada de forma compreensível se for for fácil de compreender para o destinatário do serviço. Atendendo a que norma visa, em primeira linha, a proteção dos consumidores, pensa-se que o critério pode ser a facilidade de compreensão para o consumidor médio[cite:@muller-terpitz2023; art. 30.º, n.º 44].

*b) Pelo menos na interface em linha*. O fornecedor deve disponibilizar as informações pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas. Os conceitos de "interface em linha" e "plataforma em linha" estão definidos no art. 3.º, para o qual se remete. Exige-se que a informação seja disponibilizada no mesmo local onde são apresentadas as informações sobre produto ou servço e permite-se que o fornecedor disponibilize a mesma informação em qualquer outro local da sua plataforma (/v.g./ criando, adicionalmente, uma secção dedicada na sua plataforma em linha onde seja possível pesquisar as informações relativas a todos os comerciantes que operam na sua plataforma).



* Anotação artigo 31.º :ignore:
** Trascrição do artigo :ignore:
#+BEGIN_CENTER
Artigo 31.º \\
*Conformidade desde a conceção*
#+END_CENTER

1.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes asseguram que a sua interface é concebida e organizada de forma a permitir que os comerciantes cumpram as obrigações que lhes incumbem em matéria de informação pré-contratual, conformidade e informação sobre a segurança dos produtos nos termos do direito da União aplicável.

   Em especial, o fornecedor em causa assegura que a sua interface em linha permite aos comerciantes prestar informações sobre o nome, endereço postal, número de telefone e endereço de correio eletrónico do operador económico, tal como definido no artigo 3.º, ponto 13, do Regulamento (UE) 2019/1020 e no direito da União.
2.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes asseguram que a sua interface em linha é concebida e organizada de forma a permitir que os comerciantes forneçam, pelo menos, os seguintes elementos:
   a) As informações necessárias para a identificação clara e inequívoca dos produtos ou serviços promovidos ou oferecidos aos consumidores localizados na União através dos serviços dos fornecedores;
   b) Qualquer sinal que identifique o comerciante, como a marca comercial, símbolo ou o logótipo; e
   c) Se for caso disso, as informações relativas à rotulagem e marcação em conformidade com as normas do direito da União aplicável em matéria de segurança dos produtos e conformidade dos produtos.
3.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes, envidam todos os esforços para avaliar se tais comerciantes forneceram as informações a que se referem os n.ºs 1 e 2 antes de lhes permitir oferecer os seus produtos ou serviços nessas plataformas. Após permitir ao comerciante oferecer os respetivos produtos ou serviços na sua plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes, o fornecedor envida esforços razoáveis para verificar aleatoriamente se os produtos ou serviços oferecidos foram identificados como ilegais em qualquer base de dados em linha ou interface em linha oficial, de acesso livre e legível por máquina.

** Bibliografia :ignore:
** Comentário

* Anotação artigo 32.º :ignore:
** Transcrição do artigo :ignore:
#+BEGIN_CENTER
Artigo 32.º \\
*Direito à informação*
#+END_CENTER

1.   Caso um fornecedor de uma plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes tome conhecimento, independentemente do meio utilizado, de que um produto ou serviço ilegal foi oferecido por um comerciante a consumidores localizados na União através dos seus serviços, esse fornecedor deve, na medida em que disponha dos seus dados de contacto, informar os consumidores que adquiriram o produto ou serviço ilegais através dos seus serviços do seguinte:
   a) Do facto de o produto ou serviço ser ilegal;
   b) Da identidade do comerciante; e
   c) De quaisquer meios de reparação aplicáveis.

   A obrigação estabelecida no primeiro parágrafo está limitada às aquisições de produtos ou serviços ilegais efetuadas durante os seis meses que precedem o momento em que o fornecedor tomou conhecimento da ilegalidade.
2.   Se, no caso referido no n.º 1, o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes não dispuser dos dados de contacto de todos os consumidores em causa, esse fornecedor disponibiliza ao público e torna facilmente acessível na sua interface em linha as informações sobre o produto ou serviço ilegal, a identidade do comerciante e quaisquer meios de reparação aplicáveis.

** Bibliografia :ignore:
** Comentário

* Footnotes

[fn:35] Cf. Considerando n.º 72.

[fn:34] Art. 22.º, n.º 4, da Proposta.

[fn:33] Cf. Considerando n.º 72.

[fn:32] Regulamento (UE) 2019/1150 do Parlamento Europeu e do Conselho, de 20 de junho de 2019, relativo à promoção da equidade e da transparência para os utilizadores profissionais de serviços de intermediação em linha, publicado no JO L 186 de 11.7.2019.

[fn:31] Comunicação da Comissão ao Parlamento Europeu e ao Conselho : Orientações sobre o artigo 17.º da Diretiva 2019/790 relativa aos direitos de autor no
mercado único digital, COM(2021) 288 final, 4.6.2021, pp. 9 e ss.

[fn:30] Cf. considerando n.º 73.

[fn:29] Cf. considerando n.º 73.

[fn:28] Cf. considerando n.º 73.

[fn:27] Regulamento (UE) 2015/751 do Parlamento Europeu e do Conselho, de 29 de abril de 2015, relativo às taxas de intercâmbio aplicáveis a operações de pagamento baseadas em cartões, publicado no JO L 123 de 19.5.2015.

[fn:26] "«Conta de pagamento», uma conta detida em nome de um ou mais utilizadores de serviços de pagamento, utilizada para a execução de operações de pagamento, inclusive através de uma conta específica para moeda eletrónica, na aceção do artigo 2.º, ponto 2, da Diretiva 2009/110/CE do Parlamento Europeu e do Conselho".

[fn:25] Regulamento (UE) n. ° 910/2014 do Parlamento Europeu e do Conselho, de 23 de julho de 2014 , relativo à identificação eletrónica e aos serviços de confiança para as transações eletrónicas no mercado interno e que revoga a Diretiva 1999/93/CE, publicado no JO L 257 de 28.8.2014.

[fn:24] Cf. Acórdão de 10 de julho de 2019, /Amazon EU/, C-649/17, EU:C:2019:576, considerando n.º 51.

[fn:23] Regulamento (UE) n. ° 1215/2012 do Parlamento Europeu e do Conselho, de 12 de dezembro de 2012, relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercial (reformulação), publicado no JO L 351 de 20.12.2012.

[fn:22] Directiva 2011/83/UE do Parlamento Europeu e do Conselho, de 25 de Outubro de 2011, relativa aos direitos dos consumidores, que altera a Directiva 93/13/CEE do Conselho e a Directiva 1999/44/CE do Parlamento Europeu e do Conselho e que revoga a Directiva 85/577/CEE do Conselho e a Directiva 97/7/CE do Parlamento Europeu e do Conselho Texto relevante para efeitos do EEE, publicada no JO L 304 de 22.11.2011.

[fn:21] Directiva 2006/123/CE do Parlamento Europeu e do Conselho, de 12 de Dezembro de 2006 , relativa aos serviços no mercado interno, publicada no JO L 376 de 27.12.2006.

[fn:20] Diretiva (UE) 2019/771 do Parlamento Europeu e do Conselho, de 20 de maio de 2019, relativa a certos aspetos dos contratos de compra e venda de bens que altera o Regulamento (UE) 2017/2394 e a Diretiva 2009/22/CE e que revoga a Diretiva 1999/44/CE, publicada no JO L 136 de 22.5.2019.

[fn:19] Introduzido pela Diretiva (UE) 2019/2161 do Parlamento Europeu e do Conselho de 27 de novembro de 2019 que altera a Diretiva 93/13/CEE do Conselho e as Diretivas 98/6/CE, 2005/29/CE e 2011/83/UE do Parlamento Europeu e do Conselho a fim de assegurar uma melhor aplicação e a modernização das regras da União em matéria de defesa dos consumidores, publicada no JO L 328 de 18 de dezembro de 2019.

[fn:18] Considerando n.º 72.

[fn:17] Considerando n.º 72.

[fn:16] Cf. Parecer da Comissão da Cultura e da Educação, ponto 7, constante do Relatório que contém recomendações à Comissão sobre o Ato legislativo sobre os
serviços digitais: Melhorar o funcionamento do mercado único (2020/2018(INL)), de 7.10.2020 e [cite:@hofmann2023 art. 30.º, n.º 7]

[fn:15] Cf. artigo 4.º, n.º 2, do Anexo da Recomendação 2003/361/CE.

[fn:14] Cf. Acórdãos de 27 de fevereiro de 2014, /HaTeFo/, C-110/13, EU:C:2014:114, considerando n. 32, de 24 de setembro de 2020, /NMI Technologietransfer/, C-516/19, EU:C:2020:754, considerando n.º 65, e de 10 de março de 2021, /Ertico - ITS Europe contra Comissão Europeia/, C-572/19 P, EU:C:2021:188, considerando n.º 89.

[fn:13] Cf. artigos 4.º, 5.º e 6.º do Anexo da Recomendação 2003/361/CE.

[fn:12] Cf. artigo 3.º, n.º 4, do Anexo da Recomendação 2003/261/CE.

[fn:11] Cf. artigo 3.º do Anexo da Recomendação 2003/261/CE.

[fn:10] Cf. artigo 1.º do Anexo da Recomendação 2003/261/CE.

[fn:9] Cf. artigo 2.º, n.º 2, do Anexo da Recomendação 2003/361/CE.

[fn:8] Cf. artigo 2.º, n.º 3, do Anexo da Recomendação 2003/361/CE.

[fn:7] Recomendação da Comissão, de 6 de Maio de 2003, relativa à definição de micro, pequenas e médias empresas, notificada com o número C(2003) 1422, publicada no JO L 124, de 20 de maio de 2003.

[fn:6] Cf. artigo 22.º do Regulamento (UE) 2023/988 do Parlamento Europeu e do Conselho de 10 de maio de 2023 relativo à segurança geral dos produtos, que altera o Regulamento (UE) n.o 1025/2012 do Parlamento Europeu e do Conselho e a Diretiva (UE) 2020/1828 do Parlamento Europeu e do Conselho e que revoga a Diretiva 2001/95/CE do Parlamento Europeu e do Conselho e a Diretiva 87/357/CEE do Conselho, publicado no JO L 135, de 23 de maio de 2023.

[fn:5] Cf., neste sentido, Parecer do Comité Económico e Social Europeu sobre a «Proposta de regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE», publicado no JO C 286, de 16 de julho de 2021, ponto 3.7.

[fn:4] Cf. considerando n.º 57.

[fn:3] cf. RETIFICAÇÃO da posição do Parlamento Europeu aprovada em primeira leitura, em 5 de julho de 2022, tendo em vista a adoção do Regulamento (UE) 2022/... do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE, doc. P9_TA(2022)0269 de 8 de setembro de 2022 (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)), disponível em https://www.europarl.europa.eu/doceo/document/TA-9-2022-0269_PT.html e consultada pela última vez em 20 de fevereiro de 2025.

[fn:2] Cf. o /Provisional Agreement resulting from Interinstitutional Negotiations/, de 15 de junho de 2022, doc. PE734.11, disponível em https://oeil.secure.europarl.europa.eu/oeil/en/procedure-file?reference=2020/0361(COD) e consultado pela última vez em 20 de fevereiro de 2025.

[fn:1] Cf., respetivamente, o Projeto de Relatório sobre a proposta de Regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)) - relatora: Christel Schaldemose, as alterações aprovadas, em primeira leitura, pelo Parlamento Europeu, em 20 de janeiro de 2022, sobre a proposta de regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)), disponíveis em https://oeil.secure.europarl.europa.eu/oeil/en/procedure-file?reference=2020/0361(COD) e consultados pela última vez em 20 de fevereiro de 2025, e a Proposta de REGULAMENTO DO PARLAMENTO EUROPEU E DO CONSELHO relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE - Orientação geral, de 18 de novembro de 2021, doc. 13203/21, disponível em https://eur-lex.europa.eu/legal-content/PT/HIS/?uri=CELEX:32022R2065&qid=1739909682588 e consultado pela última vez em 20 de fevereiro de 2025.
