#+title: Anotação artigos 29.º a 32.º do Regulamento dos Serviços Digitais
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+ODT_STYLES_FILE: "~/Dropbox/Bibliografia/ODT/modelo.odt"

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl chicago-fullnote-bibliography.csl




* Anotação artigo 29.º :ignore:
** Transcrição do artigo :ignore:

#+begin_quote
*Artigo 29.º (Exclusão das micro e pequenas empresas)*

1. A presente secção não se aplica aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes que sejam consideradas micro ou pequenas empresas tal como definidas na Recomendação 2003/361/CE.

   A presente secção não se aplica aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes anteriormente qualificadas para o estatuto de pequena ou microempresa tal como definidas na Recomendação 2003/361/CE durante os 12 meses seguintes à perda desse estatuto nos termos do artigo 4.º, n.º 2, exceto quando se trate de plataformas em linha de muito grande dimensão, nos termos do artigo 33.º.

2. Em derrogação do n.º 1 do presente artigo, a presente secção aplica-se aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes que tenham sido designados como plataformas em linha de muito grande dimensão nos termos do artigo 33.º, independentemente de serem ou não consideradas micro ou pequenas empresas.
#+end_quote

** Bibliografia :ignore:

[cite/nocite:@hofmann2023;@muller-terpitz2023;@wilman2024;@leitao2023]

*Bibliografia:*

#+print_bibliography:


** Comentário

*** I - Antecedentes legislativos

O artigo 16.º da Proposta estabelecia que as disposições adicionais aplicáveis aos fornecedores de plataformas em linha não seriam aplicáveis aos fornecedores que fossem considerados micro ou pequenas empresas na aceção do anexo da Recomendação 2003/361/CE, excecção semelhante à que veio a ser consagrada neste preceito.

Comparando o artigo 16.º da Proposta e o artigo 29.º do RSD, este último introduz /(i)/ um período de transição de 12 meses nos casos em que o fornecedor de plataforma em linha perca o estatuto de micro ou pequena empresa e /(ii)/ um recorte da exclusão subjetiva esclarecendo que as disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes são sempre aplicáveis quando se trate de plataformas em linha de muito grande dimensão.

O recorte da exclusão subjetiva foi introduzido pelo Parlamento Europeu e pelo Conselho[fn:1]. O período de transição surge mais tarde no processo legislativo, na sequência de negociações interinstitucionais entre o Parlamento Europeu, o Conselho e a Comissão Europeia[fn:2]. No final do processo legislativo, dividiu-se a secção 3 da Proposta (que inicia no artigo 16.º) nas atuais secção 3, relativa às disposições adicionais aplicáveis aos fornecedores de plataformas em linha (artigos 19.º a 28.º do RSD) e secção 4, relativa às disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar
contratos à distância com comerciantes (artigos 29.º a 32.º do RSD). Tal motivou uma retificação da posição adotada em primeira leitura pelo Parlamento Europeu em 5 de julho de 2022, na qual se inseriu o atual artigo 29.º do RSD[fn:3].

*** II - Ponderação de interesses

O artigo 29.º é o resultado da procura de um equilíbrio entre dois interesses: a proteção dos consumidores e o apoio e desenvolvimento das micro, pequenas e médias empresas da União Europeia. Ambos se encontram consagrados no TFUE: a proteção dos consumidores nos artigos 12.º e 169.º e o apoio e desenvolvimentos das pequanas e médias empresas nos artigos 153.º, n.º 2, al. /b)/, e 173.º, n.º 1, 2.º travessão.

A isenção subjetiva a favor das micro e pequenas empresas visa evitar encargos desproporcionados[fn:4], pois as empresas de menor dimensão poderão não conseguir suportar os custos de /compliance/ com todas as obrigações definidas no RSD e acabariam prejudicadas por um instrumento que visa também proporcionar-lhes condições de concorrência equitativas[fn:5]. As micro e pequenas empresas beneficiam de outras isenções subjetivas nos artigos 15.º, n.º 2, e 19.º do RSD, prevendo-se no artigo 91.º, n.º 2, al. /d)/, do RSD a revisão destas isenções até 17 de novembro de 2027 e a partir daí quinquenalmente. Salienta-se que o legislador europeu entendeu que as obrigações estabelecidas pelo RSD não constituem encargos desproporcionados para as médias empresas e, em contraponto, estabeleceu obrigações específicas dos prestadores de mercados em linha relacionadas com a segurança dos produtos, sem consagrar qualquer exceção para as micro e pequenas empresas no Regulamento (UE) 2023/988 relativo à segurança geral dos produtos[fn:6].

*** III - Interpretação da norma
*1. Conceitos.* Os conceitos mais relevantes do artigo 29.º são, por um lado, os conceitos de "consumidor", "comerciante", "plataforma em linha", "contrato à distância" e "plataforma em linha de muito grande dimensão" definidos, respetivamente, nos artigos 3.º, e 33.º, n.ºs 1 e 4, para os quais se remete e, por outro, os conceitos de micro e pequena empresa, definidos na Recomendação 2003/361/CE[fn:7].

Estes conceitos efetuam o recorte subjetivo de quem está sujeito às disposições adicionais consagradas na secção IV do capítulo III e de quem beneficia da exclusão prevista no artigo 29.º. Assim, e por exemplo, o fornecedor de plataforma em linha que /ou/ não permita a celebração de contratos à distância /ou/ só permita a celebração de contratos à distância entre comerciantes não está obrigado a cumprir as disposições adicionais consagradas na secção IV do capítulo III. Por outro lado, o fornecedor de plataforma em linha que permita a celebração de contratos à distância com consumidores /e/ que seja considerado uma micro ou pequena empresa na aceção da Recomendação 2003/361/CE beneficia da exclusão consagrada no artigo 29.º, n.º 1, /exceto se/ a sua plataforma em linha for designada como uma plataforma de muito grande dimensão (artigo 29.º, n.º 2).

*2. Conceitos de micro e pequena empresa.* O conceito de empresa abrange "qualquer entidade que, independentemente da sua forma jurídica, exerce uma actividade económica."[fn:10] Uma micro empresa "é definida como uma empresa que emprega menos de 10 pessoas e cujo volume de negócios anual ou balanço total anual não excede 2 milhões de euros."[fn:8] Uma pequena empresa "é definida como uma empresa que emprega menos de 50 pessoas e cujo volume de negócios anual ou balanço total anual não excede 10 milhões de euros."[fn:9] Atende-se também às relações entre empresas para efeitos de apuramento destes critérios, classificando as empresas como autónomas, parceiras ou associadas[fn:11] e esclarecendo que uma empresa não pode ser considerada uma pequena ou média empresa "se 25% ou mais do seu capital ou dos seus direitos de voto forem controlados, directa ou indirectamente, por uma ou várias colectividades públicas ou organismos públicos, a título individual ou conjuntamente."[fn:12] A Recomendação estabelece ainda os dados a considerar para cálculo dos efetivos e dos montantes financeiros[fn:13].

De acordo com o TJUE, o conceito de micro, pequenas e médias empresas (PME) da Recomendação 2003/361/CE deve ser objeto de interpretação estrita, pois as vantagens concedidas às PME constituem, muitas vezes, exceções às regras gerais[fn:14][cite:@hofmann2023, art. 29.º, n.º 7, defendem que a interpretação não deve ser estrita, mas sim tendo em conta a sua função específica].

*3. Não aplicabilidade das disposições da presente secção*. Beneficiam da não aplicabilidade desta secção todos os fornecedores de plataformas em linha que permitam a celebração de contratos à distância com consumidores que sejam, na aceção da Recomendação 2003/361/CE, uma micro ou uma pequena empresa (artigo 29.º, n.º 1, 1.º parágrafo do RSD). Como a exclusão abrange as micro e as pequenas empresas, bastará cumprir os critérios definidos na recomendação para estas últimas para beneficiar da exclusão.[cite:Cf., no mesmo sentido, @hofmann2023, art. 29.º, n.º 10]

Sendo a exclusão um benefício concedido aos os fornecedores de plataformas em linha que permitam a celebração de contratos à distância com consumidores que sejam, na aceção da Recomendação 2003/361/CE, uma micro ou uma pequena empresa, nada impede que estes voluntariamente cumpram uma ou mais das obrigações previstas nesta secção[cite:Cf., considerando n.º 57 do RSD e @muller-terpitz2023, art. 29.º, n.º 6].

*4. Perda de estatuto de micro ou pequena empresa*. Caso o fornecedor deixe de preencher os critérios para ser considerado, pelo menos, uma pequena empresa na aceção da Recomendação 2003/361/CE, ele beneficia de um período de 12 meses contados a partir da data em que perdeu o estatuto de micro ou pequena empresa (artigo 29.º, n.º 1, 2.º parágrafo). Uma empresa perde o estatuto de micro ou pequena empresa se, numa base anual, superar o limiar de efetivos e ou os limiares financeiros /e/ se tal se repetir durante dois exercícios consecutivos[fn:15]. Perdido o estatuto de micro ou pequena empresa, o fornecedor só terá a obrigação de cumprir com as normas da presente secção passados 12 meses. Este período de transição compreende-se como força de mitigar os encargos inerentes ao cumprimento das obrigações desta secção.

*5. Fornecedores de plataformas em linha de muito grande dimensão*. Os fornecedores de plataformas em linha que permitam a celebração de contratos à distância que tenham sido designadas como plataformas em linha de muito grande dimensão (cf. artigo 33.º e ss.) não beneficiam da exclusão (artigo 29.º, n.º 2, do RSD) nem do período de transição em caso de perda do estatuto de micro ou pequena empresa (artigo 29.º, n.º 1, 2.º parágrafo, /in fine/, do RSD)[cite:@leitao2023, p. 76]. Embora improvável, é possível que uma micro ou pequena empresa seja a fornecedora de uma plataforma de muito grande dimensão, pois os critérios de determinação das micro e pequenas empresas são distintos dos da determinação das plataformas em linha de muito grande dimensão[cite:@wilman2024, art. 29.º, n.º 5]. Considerando o maior alcance e impacto das plataformas em linha de muito grande dimensão (que têm um número médio mensal de destinatários activos do serviços na União Europeia igual ou superior a 45 milhões), o legislador considerou que o valor da proteção dos consumidores deve prevalecer sobre o apoio às micro e pequenas empresas, razão pela qual mesmo que o fornecedor da plataforma em linha de muito grande dimensão seja uma micro ou pequena empresa, na aceção da Recomendação 2003/361/CE, ele encontra-se obrigado ao cumprimento das disposições da presente secção.

Caso o fornecedor seja uma micro ou pequena empresa, na aceção da Recomendação 2003/361/CE, e a sua plataforma em linha que permite a celebração de contratos à distância seja designada pela Comissão Europeia como uma plataforma em linha de muito grande dimensão pode questionar-se a partir de que data devem ser cumpridas as disposições previstas nos artigos 30.º a 32.º do RSD. Resulta do artigo 33.º, n.º 6, 2.º parágrafo, do RSD que as obrigações adicionais dos fornecedores de plataformas em linha de muito grande dimensão e de motores de pesquisa em linha de muito grande dimensão no que se refere à gestão de riscos sistémicos (secção 5 do capítulo III) são aplicáveis no prazo de quatro meses após a notificação da designação ao fornecedor. Nada se prevê, porém, quanto à data em que são aplicáveis as disposições adicionais aplicáveis aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes (secção 4 do capítulo III). Parecem possíveis duas interpretações: a primeira, mais literal, é a de que as disposições da presente secção são aplicáveis a partir da data da notificação ao fornecedor da designação da sua plataforma como uma plataforma em linha de muito grande dimensão; a segunda é a de que as disposições da presente secção são aplicáveis 4 meses após a notificação ao fornecedor da designação da plataforma como plataforma em linha de muito grande dimensão, aplicando analogicamente o prazo previsto no artigo 33.º, n.º 6, 2.º parágrafo do RSD. Esta segunda opção é mais consentânea com a ponderação de interesses acima referida. Considerando o teor das obrigações previstas nos artigos 30.º a 32.º do RSD, a caracterização do fornecedor como micro ou pequena empresa na aceção da Recomendação 2003/361/CE e a classificação como plataforma em linha de muito grande dimensão depender de uma decisão da Comissão Europeia, parece adequado o prazo de quatro meses para o fornecedor assegurar o cumprimento das obrigações previstas na presente secção.

* Anotação artigo 30.º :ignore:
** Transcrição do artigo :ignore:

#+begin_quote
*Artigo 30.º (Rastreabilidade dos comerciantes)*

1.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes asseguram que os comerciantes só possam utilizar essas plataformas em linha para promover mensagens ou oferecer produtos ou serviços aos consumidores localizados na União se, antes da utilização dos seus serviços para estes fins, tiverem obtido as seguintes informações, sempre que forem aplicáveis ao comerciante:
   a) O nome, endereço postal, número de telefone e endereço de correio eletrónico do comerciante;
   b) Uma cópia do documento de identificação do comerciante ou qualquer outra identificação eletrónica, tal como definida no artigo 3.º do Regulamento (UE) n.º 910/2014 do Parlamento Europeu e do Conselho (40);
   c) Os dados da conta de pagamento do comerciante;
   d) Se o comerciante estiver inscrito num registo comercial ou noutro registo público equivalente, o registo comercial em que se encontra inscrito e o respetivo número de registo, ou forma de identificação equivalente nesse registo;
   e) Uma autocertificação do comerciante, em que se compromete a oferecer apenas produtos ou serviços que respeitem as regras aplicáveis do direito da União.
2.   Ao receber as informações a que se refere o n.º 1, e antes de permitir que o comerciante em causa utilize os seus serviços, o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes deve, seja através da utilização de uma base de dados oficial em linha ou interface em linha de acesso livre, disponibilizada por um Estado-Membro ou pela União, seja através da apresentação de pedidos ao comerciante para fornecer documentos comprovativos provenientes de fontes fiáveis, envidar todos os esforços para avaliar se as informações referidas no n.º 1, alíneas a) a e), são fiáveis e completas. Para efeitos do presente regulamento, os comerciantes são responsáveis pela exatidão das informações prestadas.

   No que diz respeito aos comerciantes que já utilizam os serviços de fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes para os fins referidos no n.º 1 em 17 de fevereiro de 2024, os fornecedores envidam todos os esforços para obter dos comerciantes em causa as informações referidas na lista no prazo de 12 meses. Se os comerciantes em causa não fornecerem as informações dentro deste prazo, os fornecedores suspendem o fornecimento dos seus serviços a tais comerciantes até que estes tenham fornecido todas as informações.
3.   Se o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes obtiver indicações suficientes de que qualquer informação a que se refere o n.º 1 obtida do comerciante em causa é inexata, está incompleta ou não está atualizada, ou se tiver motivos para o supor, esse fornecedor solicita ao comerciante que corrija a situação, sem demora ou no prazo fixado pelo direito da União e nacional.

   Se o comerciante não corrigir ou completar essas informações, o prestador de plataformas em linha que permite aos consumidores celebrar contratos à distância com comerciantes suspende rapidamente a prestação do seu serviço a esse comerciante em relação à oferta de produtos ou de serviços aos consumidores localizados na União até que o pedido tenha sido plenamente satisfeito.
4.   Sem prejuízo do disposto no artigo 4.º do Regulamento (UE) 2019/1150, caso um fornecedor de uma plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes se recuse a autorizar um comerciante a utilizar o seu serviço nos termos do n.º 1 do presente artigo, ou suspenda a sua prestação nos termos do n.º 3 do presente artigo, o comerciante em causa tem o direito de apresentar uma reclamação nos termos dos artigos 20.º e 21.º do presente regulamento.
5.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes armazenam as informações obtidas nos termos dos n.ºs 1 e 2 de forma segura durante um período de seis meses após a cessação da relação contratual com o comerciante em causa. Posteriormente, apagam as informações.
6.   Sem prejuízo do disposto no n.º 2 do presente artigo, o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes só divulga as informações a terceiros quando tal lhe for exigido nos termos do direito aplicável, incluindo as decisões a que se refere o artigo 10.º e quaisquer decisões emitidas pelas autoridades competentes dos Estados-Membros ou pela Comissão para o desempenho das suas funções nos termos do presente regulamento.
7.   O fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes disponibiliza as informações a que se refere o n.º 1, alíneas a), d) e e), na sua plataforma em linha aos destinatários do serviço de forma clara, facilmente acessível e compreensível. Essas informações ficam disponíveis pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas.
#+end_quote

** Bibliografia :ignore:

[cite/nocite:@knapp2024]

*Bibliografia:* /vide/ a indicada na anotação ao artigo 29.º;
#+print_bibliography:

** Comentário
*** I - Antecedentes legislativos
A Proposta, no seu artigo 22.º, previa um regime de rastreabilidade dos comerciantes, o qual parece ter surgigo como resposta à crítica ao modo como foi aplicado o artigo 5.º da DCE[cite:Cf. Parecer da Comissão da Cultura e da Educação, ponto 7, constante do Relatório que contém recomendações à Comissão sobre o Ato legislativo sobre os serviços digitais: Melhorar o funcionamento do mercado único (2020/2018(INL)), de 7.10.2020 e @hofmann2023, art. 30.º, n.º 7;@leitao2023, p. 76]. No decurso do processo legislativo, o artigo 22.º da Proposta foi objeto de alterações, destacando-se o aditamento de uma disposição transitória (n.º 2, 2.º parágrafo), o ajustamento do dever de verificar as informações recebidas a cargo do fornecedor, precisando que este não é responsável pela exatidão das informações (n.º 2, 1.º parágrafo), o alargamento do prazo de conservação dos dados (n.º 5) e o desenvolvimento do número relativo à conceção e organização da plataforma em linha e a sua autonomização naquele que é atualmente o artigo 31.º do RSD.

*** II - Teleologia da norma
O objetivo desta norma é "(...) contribuir para um ambiente em linha seguro, fiável e transparente para os consumidores, bem como para outras partes interessadas, como comerciantes concorrentes e titulares de direitos de propriedade intelectual (...)"[fn:17]. A norma opera com base no princípio /Know Your Business Customer/[cite:Cf., neste sentido, @wilman2024, art. 30.º, n.º 2; @hofmann2023, art. 30.º, n.º 1;@muller-terpitz2023, art. 30.º, n.º 2;@leitao2023, p. 76]. Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes devem recolher e disponibilizar informação sobre os comerciantes, antes de os autorizarem a dirigirem, através da plataforma em linha, a sua atividade aos consumidores localizados na União Europeia. A informação recolhida permitirá rastrear os comerciantes, promovendo a transparência e melhorando a proteção dos consumidores e de outras partes interessadas. Espera-se também que dissuada os comerciantes de venderem produtos ou serviços em violação das regras aplicáveis[fn:18].

*** III - Âmbito de aplicação
*1. Âmbito de aplicação subjetivo*. O artigo 30.º é aplicável aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes que não beneficiem da isenção prevista no artigo 29.º. Na concretização dos destinatários da norma são relevantes os conceitos de "consumidor", "comerciante", "plataforma em linha", e "contrato à distância" definidos no artigo 3.º, e para o qual se remete. O conceito de "plataformas em linha que permitem aos consumidores celebrar contratos à distância" é muito próximo do conceito de "mercado em linha"[fn:19], mas não inclui as plataformas que apenas permitem a celebração de contratos entre consumidores[cite:@wilman2024, p. 224, n.º 8; @hofmann2023, art. 30.º, n.º 8]. Assinala-se que apesar de o conceito de "comerciante" se encontrar definido no artigo 3.º, o considerando n.º 72 indica que "(...) qualquer comerciante, independentemente de ser uma pessoa singular ou coletiva, identificado como tal com base no artigo 6.º-A, n.º 1, alínea /b)/, da Diretiva 2011/83/UE e no artigo 7.º, n.º 4, alínea /f)/, da Diretiva 2005/29/CE, deverá ser rastreável quando oferece um produto ou serviço através de uma plataforma em linha."

*2. Âmbito de aplicação espacial*. A obrigação imposta neste artigo aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes está limitada em função do âmbito de aplicação espacial do RSD, definido no art. 2.º, para o qual se remete. Deste modo, se o comerciante não prestar as informações mencionados no n.º 1 ou se não as corrigir ou atualizar dentro do prazo fixado no n.º 3, o fornecedor da plataforma tem o dever de, respetivamente, (i) não autorizar ou (ii) suspender a utilização da plataforma pelo comerciante para promover mensagens ou oferecer produtos ou serviços /apenas aos consumidores localizados na União Europeia/. Tal significa que nestes casos o fornecedor cumpre o artigo 30.º se recusar a autorização ou suspender a utilização da sua plataforma pelo comerciante apenas aos consumidores localizados na União Europeia, por exemplo, através do mecanismo de bloqueio geogrático, permitindo que o comerciante continue a usar a plataforma para dirigir a sua atividade aos consumidores localizados fora da União Europeia[cite:Cf., no mesmo sentido, @hofmann2023, art. 30.º, n.º 12].

*3. Âmbito de aplicação material*. A ratreabilidade dos comerciantes tem por objeto a utilização das plataformas em linha para "promover mensagens e oferecer produtos ou serviços". A promoção de mensagens pelo comerciante parece reconduzível ao conceito de "anúncio publicitário" definido no artigo 3.º, al. /r)/. As noções de "produtos" e "serviços" parecem ser, respetivamente, as definidas no art. 2.º, n.º 5, da Diretiva relativa a certos aspetos dos contratos de compra e venda de bens[fn:20] e no art. 4.º, n.º 1, da Diretiva serviços[fn:21]. O artigo, ao mencionar a promoção de mensagens e a oferta de produtos e serviços, /não/ abrange a conclusão do contrato[cite:Cf., neste sentido, @hofmann2023, art. 30.º, n.º 12;@muller-terpitz2023, art. 30.º, n.º 6].

*** IV - Recolha de informações (n.º 1)
*4. Introdução*. Resulta do n.º 1 que os fornecedores das plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes têm a obrigação de não permitir a utilização da sua plataforma pelo comerciante para promover mensagens ou oferecer produtos e serviços aos consumidores localizados na União Europeia /antes/ de recolhida a informação elecanda neste número.

Do n.º 1 não parece resultar um dever, mas sim ónus do comerciante prestar a informação. Dito de outra forma, o comerciante não se encontra obrigado pelo artigo 30.º a prestar a informação ao fornecedor da plataforma em linha, mas se não o fizer não poderá utilizar a plataforma para promover mensagens ou oferecer produtos ou serviços aos consumidores localizados na União Europeia[cite:@hofmann2023, art. 30.º, n.º 12]. O artigo não impede que o fornecedor permita que o comerciante: /(i)/ utilize a plataforma em linha em momento anterior ao da prestação da informação para realizar atos diferentes da promoção de mensagens ou oferta de produtos ou serviços, como, por exemplo, a organização da sua "loja virtual" na plataforma em linha[cite:@hofmann2023, art. 30.º, n.º 11]; /(ii)/ dirija a sua atividade para os consumidores localizados fora da União Europeia (cf. /supra/ *III.2.*).

*5. Informações a obter*. *a) Nome, endereço postal, número de telefone e endereço de correio eletrónico do comerciante*. Esta informação já é exigida no artigo 6.º da Diretiva relativa aos direitos dos consumidores[fn:22] e visa facilitar a identificação e contacto com o comerciante e promover um ambiente em linha mais seguro, em primeira linha para os consumidores. Neste contexto, o comerciante (seja ele pessoa singular ou coletiva) deve indicar o seu nome completo. O endereço postal deve corresponder à morada onde o comerciante pode ser judicialmente demandado (podendo, consoante os casos, ser uma das que resulta da aplicação dos artigos 4.º, 7.º, n.º 5, ou 17.º, n.º 2, conjugados com o artigo 63.º, todos do Regulamento Bruxelas I /bis/[fn:23]). A indicação de um número telefone é obrigatória, divergindo do que decidiu o TJUE no contexto da Diretiva relativa aos direitos dos consumidores[fn:24]. Por fim, o endereço de correio eletrónico indicado deve permitir o efetivo contacto com o comerciante e não pode ser um endereço configurado com respostas automáticas que remetam para outros meios de contacto[cite:@hofmann2023, art. 30.º, n.º 19].

*b) Cópia do documento de identificação do comerciante ou qualquer outra identificação eletrónica*. O fornecedor deve receber cópia do documento de identificação do comerciante. No caso de comerciantes com cartão do cidadão português, a cópia pode ser substituída pelo documento pdf gerado pela aplicação móvel gov.pt, ao abrigo do Regulamento eIDAS[fn:25].

*c) Dados da conta de pagamento do comerciante*. O fornecedor deve receber informações sobre a conta de pagamento do comerciante. A noção de "conta de pagamento" não está definida no RSD, mas corresponde à definição constante do artigo 2.º, n.º 22[fn:26], do Regulamento relativo às taxas de intercâmbio aplicáveis a operações de pagamento baseadas em cartões[fn:27].

*d) Registo comercial ou outro registo público equivalente*. Caso o comerciante esteja inscrito no registo comercial ou em outro registo público equivalente, o fornecer deve receber a informação de que o comerciante se encontra inscrito e o seu número de registo.

*e) Autocertificação do comerciante*. O fornecedor deve receber uma autocertificação do comerciante em que este se compromete a oferecer apenas produtos ou serviços que respeitem as regras aplicáveis do direito da União. Esta autocertificação tem um carácter geral[cite:@wilman2024, art. 30.º, n.º 7]. É dúvidoso que esta autocertificação seja eficaz na promoção de um ambiente em linha mais seguro ou seja um dissuasor para os comerciantes que pretendam dirigir a sua atividade para o mercado da União Europeia sem cumprir as regras que aí são aplicáveis[cite:Suscitando dúvidas similares, cf. @hofmann2023, art. 30.º, n.º 23;@muller-terpitz2023, art. 30.º, n.º 14].

*** V - Disposição transitória (n.º 2, 2.º parágrafo)
A recolha de informação prevista no n.º 1 deste artigo parte do pressuposto de que o comerciante ainda não utiliza a plataforma em linha do fornecedor. Se o comerciante, à data da entrada em aplicação das normas do RSD, já utilizava a plataforma em linha, o fornecedor deve solicitar-lhe a prestação das informações elencadas no n.º 1. Se os comerciantes em causa não fornecerem as informações até 17 de fevereiro de 2025, os fornecedores suspendem o fornecimento dos seus serviços a tais comerciantes até que estes tenham fornecido todas as informações.

*** VI - Obrigação de avaliação prévia da informação obtida (n.º 2, 1.º parágrafo)
*6. Regime*. Recebidas as informações elencadas no n.º 1, o fornecedor deve envidar todos os esforços para avaliar se as informações recebidas são fiáveis e completas antes de permitir a utilização da sua plataforma pelo comerciante para propor mensagens e oferecer produtos ou serviços aos consumidores localizados na União Europeia. Esta obrigação de avaliação prévia da informação obtida é uma novidade.

*7. Objeto da avaliação*. O fornecedor deve avaliar se as informações são fiáveis e completas. Verificar se as informações estão ou não completas não parece suscitar dificuldades de maior[cite:@wilman2024, art. 30.º, n.º 15]. Para avaliar a fiabilidade das informações sugere-se a utilização de "bases de dados oficiais em linha e interfaces em linha de livre acesso, como registos comerciais nacionais e o Sistema de Intercâmbio de Informações sobre o IVA, ou solicitar aos comerciantes em causa que forneçam documentos comprovativos fiáveis, como cópias de documentos de identidade, extratos certificados de contas de pagamento, certificados de empresa e certidões de registo comercial", admitindo-se ainda o recurso "a outras fontes, disponíveis para utilização à distância, que proporcionem um grau de
fiabilidade semelhante para efeitos de cumprimento desta obrigação"[fn:28]. A verificação da fiabilidade da autocertificação parece problemática, uma vez que incide sobre comportamentos futuros[cite:@wilman2024, art. 30.º, n.º 16].

O fornecedor não é obrigado a verificar a exatidão das informações recebidas. O responsável pela exatidão das informações é o comerciante (art. 30.º, n.º 2, 1.º parágrafo, /in fine/ do RSD). Se, no entanto, o fornecedor tiver conhecimento de que as informações são inexatas, não deve autorizar a utilização da plataforma antes da correção das mesmas pelo comerciante[cite:Cf., neste sentido, @hofmann2023, art. 30.º, n.º 29].

*8. Critério de diligência*. Estabelece-se que o fornecedor deve "envidar todos os esforços" para avaliar se as informações são fiáveis e completas. Esta expressão deve ser interpretada com cautela e compaginada com o esclarecimento no considerando n.º 73 de que "os fornecedores de plataformas em linha em causa não deverão ser obrigados a realizar exercícios de apuramento de factos em linha excessivos ou dispendiosos, nem a efetuar verificações desproporcionadas no local". Considera-se que o critério de diligência a adotar é o de "melhores esforços"[cite:@wilman2024, art. 30.º, n.º 13;@hofmann2023, art. 30.º, n.º 25;@muller-terpitz2023, art. 30.º, n.º 18], correspondente à versão em língua inglesa /"best efforts"/ e também ao artigo 17.º, n.º 4, da DMD. O conceito de "melhores esforços" não se encontra definido no RSD e deve ser objeto de interpretação autónoma, a qual deve atender à finalidade e objetivos do artigo 31.º e do RSD. Ainda assim, pensa-se que é possível traçar paralelos com a utilização do conceito no artigo 17.º, n.º 4, da DMD e tomar em consideração as orientações da Comissão Europeia sobre este conceito nessa sede[fn:31]. Não se visa garantir um determinado resultado, o que compreende em face do art. 8.º do RSD e da vontade de não impor encargos desproporcionados[fn:30]. Deve ser feita uma análise casuística, atendendo às cirscunstâncias do caso concreto e à complexidade da avaliação, sempre tendo em atenção o princípio da proporcionalidade. Pode questionar-se se o fornecedor empregou os seus "melhores esforços" se efetuou a sua avaliação com base num (e apenas um) dos elementos elencados no art. 2.º, n.º 2[cite:@hofmann2023, art. 30.º, n.º 26]. Atendendo à natureza casuística do conceito, a resposta afirmativa ou negativa a esta questão dependerá das circunstâncias do caso concreto.

*** VII - Informações inexatas, incompletas ou desatualizadas (n.º 3)

*9. Regime*. Se o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes obtiver indicações suficientes ou motivos para supor que qualquer informação a que se refere o n.º 1 obtida do comerciante em causa é inexata, incompleta ou está desatualizada, o fornecedor deve solicitar ao comerciante que corrija a situação, sem demora ou no prazo fixado pelo direito da União e nacional.

*10. Tipologia de informações*. O n.º 3 refere informações inexatas, incompletas ou desatualizadas. São informações inexatas aquelas que não correspondem à realidade (/v.g./: o comerciante indica um número de telefone que não lhe pertence). São informações incompletas aquelas em que não consta a totalidade da informação necessária (/v.g./: o comerciante indica a a rua, cidade e país da sua sede, mas não indica o n.º da porta). Uma informação desatualizada é uma informação que era exata e completa quando foi prestada, mas com o decurso de tempo se tornou inexata (/v.g./: o comerciante indicou a morada da sede, mas, posteriormente, transferiu a sede para outro local). Na verdade, crê-se que as informações desatualizadas serão sempre informações inexatas e, por isso, duvida-se que as mesmas tenham autonomia face a estas últimas[cite:@muller-terpitz2023, art. 30.º, n.º 31].

*11. Indicações suficientes ou motivos para supor*. O dever do fornecedor de solicitar a correção ao comerciante surge quando obtiver indicações suficientes ou motivos para supor que as informações prestadas são inexatas, incompletas ou desatualizadas. O conceito de indicações suficientes não é definido no RSD. Pensa-se que será uma indicação suficiente, por exemplo, uma comunicação de um consumidor a informar, por exemplo, que o endereço de correio eletrónico disponibilizado pelo comerciante não permite o contacto. Quanto aos motivos para supor, considera-se que eles permitem ao fornecedor efetuar uma verificação oficiosa da correção, completude e atualidade das informações prestadas pelo comercianteo[cite:@hofmann2023, art. 30.º, n.ºs 36 e 37;@muller-terpitz2023, art. 30.º, n.º 28].

*12. Correção das informações*. O fornecedor deve solicitar ao comerciante que corrija a situação, sem demora ou no prazo fixado pelo direito da União e nacional. Visa-se uma correção sem atrasos indevidos. Não parece possível fixar o prazo de forma rígida, uma vez que o mesmo deverá atender às circunstâncias do caso concreto, nomeadamente à dificuldade de efetuar a correção[cite:@hofmann2023, art. 30.º, n.º 42].

*13. Consequência jurídica*. Efetuada a solicitação de correção das informações, o comerciante pode /(i)/ corrigir as informações dentro do prazo fixado, /(ii)/ corrigir as informações fora do prazo ou /(iii)/ pode não corrigir as informações. No primeiro caso, o fornecedor deve manter o serviço e pode, ao abrigo do n.º 3, examinar as informações corrigidas para apurar se há novas informações inexatas, incompletas ou desatualizadas. Nos segundo e terceiro casos, o fornecedor deve suspender rapidamente o serviço que presta ao comerciante, mas apenas quanto aos consumidores localizados na União Europeia (o que pode ser feito recorrendo ao mecanismo de bloqueio geográfico). A diferença entre o segundo e terceiro casos, encontra-se na possibilidade de o comerciante vir a efetuar, tardiamente, a correção das informações. Nesse caso é sustentado que o fornecedor deve examinar a informação antes de levantar a suspensão[cite:@hofmann2023, art. 30.º, n.º 44].

*** VIII - Direito de apresentar uma reclamação (n.º 4)

Nos casos em que um fornecedor de uma plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes se recuse a autorizar um comerciante a utilizar o seu serviço ao abrigo do n.º 1 ou suspenda a utilização do seu serviço ao abrigo do n.º 3, o comerciante tem o direito de apresentar uma reclamação nos termos dos artigos 20.º e 21.º do RSD, em acréscimo ao direito previsto no artigo 4.º, n.º 3, do Regulamento P2B[fn:32].

*** IX - Conservação dos dados (n.º 5)
O fornecedor de plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes está obrigado a armazenar as informações que obtenha ao abrigo dos n.ºs 1 e 2 de forma segura até que decorram 6 meses contados do termo da relação contratual com o comerciante. A Proposta previa a conservação apenas até ao termo da relação contratual[fn:34]. O alargamento do prazo de conservação constitui um reforço da proteção dos consumidores e pode ser necessário no contexto do art. 32.º[cite:@hofmann2023, art. 30.º, n.º 48]. Durante esse período os dados devem conservados de forma segura, isto é utilizando meios tecnológicos adequados para garantir a segurança dos dados recebidos, atendendo também à natureza destes[cite:@muller-terpitz2023, art. 30.º, n.º 38]. Findo o prazo de conservação, o fornecedor deve apagar os dados, salvo se estiver sujeito a outras eventuais "obrigações de conservar determinados conteúdos durante períodosde tempo mais longos previstas no direito da União ou direito nacional que seja conforme com direito da União"[fn:35].

Esta obrigação de tratamento de dados visa "permitir que sejam apresentadas reclamações contra o comerciante ou que sejam cumpridas as decisões relacionadas com o comerciante" e é considerada pelo legislador europeu "necessária e proporcionada para que as informações possam ser acedidas, nos termos da legislação aplicável, nomeadamente em matéria de proteção de dados pessoais, por autoridades públicas e entidades privadas com um interesse legítimo, incluindo através das decisões de prestação de informações referidas no presente regulamento"[fn:33].

*** X - Divulgação das informações (n.ºs 6 e 7)
*14. Considerações gerais*. Os n.ºs 6 e 7 regulam a divulgação das informações obtidas ao abrigo dos n.ºs 1 e 2 pelo fornecedor. O n.º 6 regula a divulgação das informações a terceiros. O n.º 7 obriga o fornecedor a publicar, pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas, as informações obtidas ao abrigo do n.º 1, alíneas /a)/, /d)/ e /e)/ (cf. /supra/ *IV.5.a), d)* e *e)*). Deste modo, e como regra geral, a informação obtida ao abrigo do n.º 1, alíneas /a)/, /d)/ e /e)/, ficará disponível ao público em geral, pois as plataformas em linha que permitem a celebração de aos consumidores celebrar contratos à distância com consumidores não limitam a visualização de informações sobre produtos e serviços na sua plataforma em linha aos cibernautas que criaram uma conta na plataforma e acederam à mesma antes de navegarem pela plataforma. Deste modo, o n.º 6 releva, primordialmente, para conseguir o acesso às informações sobre os dados de identificação (n.º 1, alínea /b)/) e os dados da conta de pagamento (n.º 1, alínea /c)/) do comerciante.

*15. Divulgação das informações a terceiros (n.º 6)*. O fornecedor só pode divulgar as informações obtidas ao abrigo do n.º 1 e 2 a terceiros quando tal lhe seja exigido nos termos do Direito aplicável. O n.º 6 enuncia, sem limitar, que o fornecedor deve divulgar as informações quando tal lhe seja exigido no contexto de uma decisão do artigo 10.º do RSD ou de quaisquer decisões emitidas pelas autoridades competentes dos Estados-Membros ou pela Comissão para o desempenho das suas funções nos termos do presente regulamento.

*16. Divulgação de informações na plataforma em linha (n.º 7)*. As informações relativas ao nome, endereço postal, número de telefone e endereço de correio eletrónico do comerciante (n.º 1, alínea /a)/), ao registo comercial ou outro registo público equivalente, se o comerciante estiver inscrito (n.º 1, alínea /b)/) e à autocertificação (n.º 1, alínea /e)/) devem ser disponibilizadas aos destinatários de forma clara, facilmente acessível e compreensível e pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas.

*a) Divulgação de forma clara, facilmente acessível e compreensível*. A divulgação das informações deve ser efetuada de forma clara, facilmente acessível e compreensível. A informação é divulgada de forma clara se for facilmente identificável, procurando evitar-se ambiguidades e dúvidas interpretativas[cite:@muller-terpitz2023, art. 30.º, n.º 43]. A informação é divulgada de forma facilmente acessível se o destinatário do serviço consegue aceder à informação sem necessitar de pesquisar muito por ela[cite:@hofmann2023, art. 30.º, n.º 51], não devendo a interface em linha constituir um entrave ao acesso à informação[cite:Cf., no contexto do artigo 14.º, @knapp2024, p. 113]. Por fim, a informação é divulgada de forma compreensível se for for fácil de compreender para o destinatário do serviço. Atendendo a que norma visa, em primeira linha, a proteção dos consumidores, o critério pode ser a facilidade de compreensão para o consumidor médio[cite:@muller-terpitz2023, art. 30.º, n.º 44].

*b) Pelo menos na interface em linha*. O fornecedor deve disponibilizar as informações pelo menos na interface em linha da plataforma em linha onde as informações sobre o produto ou sobre o serviço são apresentadas. Os conceitos de "interface em linha" e "plataforma em linha" estão definidos no art. 3.º, para o qual se remete. Exige-se que a informação seja disponibilizada no mesmo local onde são apresentadas as informações sobre produto ou servço e permite-se que o fornecedor disponibilize a mesma informação em qualquer outro local da sua plataforma (/v.g./ criando, adicionalmente, uma secção dedicada na sua plataforma em linha onde seja possível pesquisar as informações relativas a todos os comerciantes que operam na sua plataforma).



* Anotação artigo 31.º :ignore:
** Trascrição do artigo :ignore:
#+begin_quote

*Artigo 31.º (Conformidade desde a conceção)*

1.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes asseguram que a sua interface é concebida e organizada de forma a permitir que os comerciantes cumpram as obrigações que lhes incumbem em matéria de informação pré-contratual, conformidade e informação sobre a segurança dos produtos nos termos do direito da União aplicável.

   Em especial, o fornecedor em causa assegura que a sua interface em linha permite aos comerciantes prestar informações sobre o nome, endereço postal, número de telefone e endereço de correio eletrónico do operador económico, tal como definido no artigo 3.º, ponto 13, do Regulamento (UE) 2019/1020 e no direito da União.
2.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes asseguram que a sua interface em linha é concebida e organizada de forma a permitir que os comerciantes forneçam, pelo menos, os seguintes elementos:
   a) As informações necessárias para a identificação clara e inequívoca dos produtos ou serviços promovidos ou oferecidos aos consumidores localizados na União através dos serviços dos fornecedores;
   b) Qualquer sinal que identifique o comerciante, como a marca comercial, símbolo ou o logótipo; e
   c) Se for caso disso, as informações relativas à rotulagem e marcação em conformidade com as normas do direito da União aplicável em matéria de segurança dos produtos e conformidade dos produtos.
3.   Os fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes, envidam todos os esforços para avaliar se tais comerciantes forneceram as informações a que se referem os n.ºs 1 e 2 antes de lhes permitir oferecer os seus produtos ou serviços nessas plataformas. Após permitir ao comerciante oferecer os respetivos produtos ou serviços na sua plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes, o fornecedor envida esforços razoáveis para verificar aleatoriamente se os produtos ou serviços oferecidos foram identificados como ilegais em qualquer base de dados em linha ou interface em linha oficial, de acesso livre e legível por máquina.
#+end_quote


** Bibliografia :ignore:

*Bibliografia:* /vide/ a indicada na anotação ao artigo 29.º.

** Comentário
*** I - Antecedentes legislativos
O artigo 22.º da Proposta, relativo à rastreabilidade dos comerciantes, previa apenas um número (o n.º 7) dedicado à conceção e organização da plataforma em linha. Durante o processo legislativo, a Comissão dos Assuntos Jurídicos propôs o aditamento à Proposta de um novo artigo 22a[fn:36] sobre a matéria. Na sequência de negociações interinstitucionais entre o Parlamento Europeu, o Conselho e a Comissão Europeia, o n.º 7 do artigo 22.º e o novo artigo 22a foram reunidos num único preceito, com algumas alterações e precisões de redação, destacando-se a redução das obrigações de verificação agora previstas no artigo 31.º, n.º 3[fn:2].

*** II - Teleologia da norma
O artigo 31.º visa reforçar a proteção dos consumidores, através da conceção técnica das plataformas em linha (/law by design/)[cite:@hofmann2023, art. 30.º, n.º 3;@muller-terpitz2023, art. 30.º, n.º 2]. O Direito Europeu tem um hoje um conjunto vasto de obrigações que impendem sobre o comerciante e que visam proteger o consumidor, como os artigos 6.º e 8.º da Diretiva relativa aos direitos dos consumidores, o artigo 7.º da Diretiva relativa às práticas comerciais desleais[fn:37], os artigos 5.º e 6.º da DCE e o artigo 3.º da Diretiva em matéria de indicações dos preços dos produtos oferecidos aos consumidores[fn:38][fn:39]. Com este preceito, impõem-se aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes três obrigações distintas. Em primeiro lugar, a obrigação de conceber e organizar a sua interface de forma a que os comerciantes cumpras as suas obrigações em matéria de informação pré-contratual, conformidade e informação sobre a segurança dos produtos nos termos do direito da União aplicável (n.ºs 1 e 2). Em segundo lugar, a obrigação de verificar se os comerciantes prestaram as informações a que se referem os n.ºs 1 e 2 antes de permitirem que estes ofereçam os seus produtos ou serviços na plataforma em linha (n.º 3, primeiro período). Em terceiro lugar, a obrigação de verificar, posteriormente e por amostragem, se os produtos ou serviços oferecidos na sua plataforma em linha foram identificados como ilegais (n.º 3, segundo período). Estas obrigações que são agora impostas aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes visam garantir a aplicação do Direito e assim melhor proteger os consumidores.

*** III - Âmbito de aplicação

*1. Âmbito de aplicação subjetivo*. O artigo 31.º é aplicável aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes que não beneficiem da isenção prevista no artigo 29.º. Na concretização dos destinatários da norma são relevantes os conceitos de "consumidor", "comerciante", "plataforma em linha", e "contrato à distância" definidos no artigo 3.º, e para o qual se remete. O conceito de "plataformas em linha que permitem aos consumidores celebrar contratos à distância" é muito próximo do conceito de "mercado em linha"[fn:19], mas não inclui as plataformas que apenas permitem a celebração de contratos entre consumidores[cite:@muller-terpitz2023, art. 31.º, n.º 4;no contexto do artigo 30.º, transponível também para este preceito, cf. @wilman2024, p. 224, n.º 8;@hofmann2023, art. 30.º, n.º 8].

*2. Âmbito de aplicação espacial*. A obrigação imposta neste artigo aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes está limitada em função do âmbito de aplicação espacial do RSD, definido no art. 2.º, para o qual se remete. Apesar de apenas a alínea /a)/ do n.º 2 mencionar expressamente a localização dos consumidores na União Europeia, entende-se que todas as obrigações estabelecidas pelo artigo 31.º só são aplicáveis quando os comerciantes querem dirigir ou dirigem a sua atividade aos consumidores localizados na União Europeia. Assim, e por exemplo, o artigo 31.º não é aplicável e o fornecedor da plataforma em linha pode autorizar a utilização da sua plataforma em linha por um comerciante nos casos em que - através de um mecanismo tecnológico, como o bloqueio geográfico - este só possa dirigir a sua atividade para consumidores localizados /fora/ da União Europeia.

*** IV - Obrigação de conceção e organização da interface em linha (n.ºs 1 e 2)
*3. A regra geral (n.º 1, 1.º parágrafo)*. Os fornecedores devem assegurar que a interface em linha das suas plataformas em linha são concebidas e organizadas de modo a que os comerciantes possam cumprir as suas obrigações em matéria de informação pré-contratual, conformidade e informação sobre a segurança dos produtos.

O forneceder deve, por isso, planear e implementar o interface em linha da sua plataforma em linha de modo a promover o cumprimento das obrigações dos comerciantes naquelas matérias.

*a) Interface em linha*. Interface em linha é definida no artigo 3.º, al. /m)/, do RSD como "quaisquer programas informáticos, incluindo um sítio Web ou uma parte deste, e aplicações, incluindo aplicações móveis;". Em linguagem não ténica, entende-se que o interface em linha é constituído pelos programas informáticos, entendidos de forma ampla, que permitem ao comerciante aceder e interagir com a plataforma em linha.

*b) Obrigações dos comerciantes*. O interface deve ser concebido e organizado de modo a promover o cumprimento pelos comerciantes das suas obrigações em três matérias distintas:

*(1) Informações pré-contratuais*. Nesta matéria, o considerando n.º 74 dá como exemplos os artigos 6.º e 8.º da Diretiva relativa aos direitos dos consumidores, o artigo 7.º da Diretiva relativa às práticas comerciais desleais[fn:37], os artigos 5.º e 6.º da DCE e o artigo 3.º da Diretiva em matéria de indicações dos preços dos produtos oferecidos aos consumidores. Não há, atualmente, uma uniformização destas obrigações de informação no Direito da União Europeia[cite:Cf., considerando que a mesma seria desejável, @hofmann2023, art. 31.º, n.º 1] e, portanto, o fornecedor deve conceber e organizar o interface da sua plataforma em linha de modo a que o comerciante possa cumprir com todas as suas obrigações de informação pré-contratual.

*(2) Conformidade*. Esta matéria não constava da Proposta, que se referia apenas às informações pré-contratuais e à informação sobre a segurança dos produtos[cite:Cf. artigo 22.º, n.º 7, da Proposta. @wilman2024, art. 31.º, n.º 6 consideram não ser claro a que se refere este aditamento]. Parece possível incluir aqui os produtos que, cumpridos os requisitos de conformidade previstos no Direito da União, têm direito a uma declaração UE de confomidade e a ostentar uma marcação UE de conformidade. A plataforma em linha terá, pelo menos, de permitir que os comerciantes forneçam a marcação UE de conformidade dos seus produtos, conforme previsto no n.º 2, al. /c)/, deste artigo[cite:@hofmann2023, art. 31.º, n.º 13].

*(3) Informação sobre a segurança dos produtos*. Nesta matéria, releva principalmente o Regulamento relativo à segurança geral dos produtos que, no seu artigo 19.º, estabelece que quando os operadores económicos disponibilizem produtos no mercado em linha ou através de outros meios de venda à distância, a oferta desses produtos deve indicar de forma clara e visível um conjunto mínimo de informações, a saber: (i) nome, denominação comercial registada ou marca registada do fabricante e endereço postal e eletrónico para contacto; (ii) nome, endereço postal e eletrónico do operador económico estabelecido na União Europeia, quando o fabricante não esteja estabelecido na União Europeia; (iii) informações que permitam identificar o produto, incluindo uma imagem do mesmo, o seu tipo e qualquer outro identificador do produto; e (iv) alertas ou informações de segurança que devem ser apostas no produto ou na embalagem ou incluídas num documento que acompanhe o produto, de acordo com o presente regulamento ou com a legislação de harmonização da União aplicável, numa língua que possa ser facilmente compreendida pelos consumidores, conforme determinado pelo Estado-Membro em que o produto é disponibilizado no mercado.

*4. Informações mínimas (n.º 1.º, 2.º parágrafo e n.º 2)*. A interface da plataforma em linha deve permitir aos comerciantes fornecer um conjunto /mínimo/ de informações. Esse elenco parece estar contido no n.º 2, atendendo à sua redação ("a sua interface em linha é concebida e organizada de forma a permitir que os comerciantes forneçam, /pelo menos/, os seguintes elementos"). A verdade, porém, é que ao conjunto de informações elencadas no n.º 2 se deve aditar as informações sobre o operador ecónomico (n.º 1, 2.º parágrafo) e se deve tomar em consideração as concretizações efetuadas no artigo 22.º, n.º 9, do Regulamento relativo à segurança geral dos produtos. Assim, e no que respeita aos produtos, esta norma exige adicionalmente que a interface assegure que as informações são apresentadas ou facilmente acessíveis pelos consumidores na lista de produtos.

*a) Informações sobre o operador económico*. A interface deve permitir que o comerciante preste informações sobre o o nome, endereço postal, número de telefone e endereço de correio eletrónico do operador económico. O conceito de operador económico é definido como o fabricante, o mandatário, o importador, o distribuidor, o prestador de serviços de execução ou qualquer outra pessoa singular ou coletiva sujeita a obrigações no que respeita ao fabrico de produtos, disponibilizando-os no mercado ou colocando-os em serviço de acordo com a legislação de harmonização aplicável da União[fn:42]. A relevância desta informação poderá estar relacionada com as dificuldades sentidas pelas autoridades de fiscalização do mercado na identificação dos agentes económicos relevantes[cite:@hofmann2023, art. 30.º, n.º 18]. Releva-se, no que respeita aos produtos, o disposto no artigo 22.º, n.º 9, alíneas /a)/ e /b)/, do  Regulamento relativo à segurança geral dos produtos, o qual parece explicitar que o comerciante deve prestar esta informação sobre fabricante do produto, quando este se encontre localizado na União Europeia. Estranhamente, estas alíneas, ao contrário do n.º 1, 2.º parágrafo, do RSD não exigem a indicação de um número de telefone. Seria desejável que se tivesse garantido uma uniformização da informação a prestar pelo comerciante. Não se vislumbra nesta omissão uma vontade de suprimir a informação do número telefónico, pelo que se entende que esta informação deve manter-se como parte integrante do conjunto de informação mínima.

*b) Informações sobre a identificação do produto ou do serviço*. A interface da plataforma em linha deve permitir que os comerciantes prestem a informação necessária para identificação de cada um dos produtos ou serviços por si promovidos ou oferecidos aos consumidores localizados na União Europeia. No que respeita aos produtos, o artigo 22.º, n.º 9, alínea /c)/, do  Regulamento relativo à segurança geral dos produtos concretiza que as informações que permitem identificar um produto incluem uma imagem do mesmo, o seu tipo e qualquer outro identificador do produto.

*c) Sinal identificativo do comerciante*. A interface da plataforma em linha deve permitir que o comerciante forneça qualquer sinal que o identifique, como a marca comercial, símbolo ou logótipo. Não há qualquer referência a esta tipologia de informação no artigo 22.º, n.º 9, do Regulamento relativo à segurança geral dos produtos, o que talvez se possa explicar porque o mesmo parece ter como propósito a concretização dos requisitos constantes do artigo 31.º, n.ºs 1 e 2, do RSD no que respeita à segurança dos produtos.

*d) Informações relativas à rotulagem e marcação em conformidade*. A interface da plataforma em linha deve permitir que o comerciante preste nformações relativas à rotulagem e marcação em conformidade com as normas do direito da União aplicável em matéria de segurança dos produtos e conformidade dos produtos. Em matéria de segurança de produtos, temos, por exemplo, a obrigação de classificar, rotular e embalar de acordo com as regras em vigor as substâncias e misturas explosivas, antes de as colocar no mercado[fn:43]. Sobre a conformidade de produtos, remete-se para o exemplo dado /supra/ em *IV.3.b).(2)*.

*** V - Obrigações de avaliação e verificação (n.º 3)
*5. Introdução*. O fornecedor tem a obrigação de avaliar se o comerciante forneceu o conjunto de informações mínimas antes de lhe permitir a utilização da plataforma em linha para oferecer produtos ou serviços aos consumidores localizados na União Europeia. Após ter dado essa autorização de utilização da plataforma em linha, o fornecedor tem uma obrigação de verificar, aleatória e periodicamente, se os produtos ou serviços oferecidos na sua plataforma em linha foram identificados como ilegais em qualquer base de daos em linha ou interface em linha oficial, de acesso livre e legível por máquina.

*6. Obrigação prévia de avaliação (n.º 3, 1.º período)*. Compete ao fornecedor avaliar se o comerciante prestou todas as informações a que se referem os n.ºs 1 e 2 antes de o autorizar a utilização da plataforma em linha ppara oferecer produtos ou serviços aos consumidores localizados na União Europeia.

O objeto desta avaliação é apenas o de determinar se o comerciante prestou todas as informações, ou seja, se a prestação da informação pelo comerciante foi completa[cite:Contra, @wilman2024, art. 31.º, n.º 13, sustentam que o fornecedor só tem de verificar que a informação foi fornecida, não tendo de verificar se a mesma é fiável e completa] (contraste-se com o artigo 30.º, n.º 2 (cf. /supra/ *30.º.VI.6.*), que exige que o fornecedor avalie se as informações são fiáveis e completas). O fornecedor não está obrigado a avaliar a exatidão das informações[cite:Cf. considerando n.º 74 e @hofmann2023, art. 31.º, n.º 26;@muller-terpitz2023, art. 31.º, n.º 17].

O critério da diligência é também aqui o critério dos "melhores esforços", pelo que se remete /supra/ para *30.º.VI.7.*.

Se o forneceder concluir que as informações fornecidas estão incompletas, ele deve assegurar-se de que não são oferecidos produtos ou serviços enquanto essas informações não estiverem completas[fn:44].

Ao contrário do que sucede no artigo 30.º, n.º 2, não foi estabelecida aqui qualquer disposição transitória para regular os casos dos comerciantes que já se encontravam a oferecer produtos ou serviços através da plataforma em linha aos consumidores localizados na União Europeia[cite:@muller-terpitz2023, art. 31.º, n.º 18, consideram que, em face desta omissão, não é claro como proceder nestes casos]. Sustenta-se, tentativamente e atendendo à teleologia da norma, que o fornecedor deve conceder um prazo razoável para o comerciante fornecer as informações a que se referem os n.ºs 1 e 2. Findo esse prazo, se as informações não forem fornecidas ou o forem de modo incompleto, deve suspender a oferta dos produtos ou serviços na plataforma aos consumidores localizados na União Europeia.

*7. Obrigação posterior de verificação (n.º 3, 2.º período)*. Após autorizar a utilização da plataforma, o fornecedor deve envidar esforços razoáveis para verificar aleatoriamente se estão a ser oferecidos produtos ou serviços na sua plataforma em linha que foram identificados como ilegais.

O objeto desta verificação é determinar se algum ou alguns dos produtos ou serviços oferecidos na plataforma foram identificados como ilegais em qualquer base de dados em linha ou interface em linha oficial, de acesso livre e legível por máquina, disponíveis num Estado-Membro ou na União.

Os conceitos de "produto ilegal" e "serviço ilegal" não são definidos no RSD. O RSD define o conceito de "conteúdos ilegais" no artigo 3.º, alínea /h)/, para cuja anotação se remete. Traçando um paralelo com o conceito de conteúdos ilegais, dir-se-á que produtos ou serviços ilegais são os que não estejam em conformidade com o direito da União ou com o direito de qualquer um dos Estados-Membros que seja conforme com o direito da União, independentemente do objeto ou da natureza precisa desse direito[cite:Cf., neste sentido, @muller-terpitz2023, art. 31.º, n.º 20;@hofmann2023, art. 32.º, n.º 18].

O critério de diligência é o de "esforços razoáveis". Trata-se de um crivo menos exigente do que os "melhores esforços" consagrado no 1.º período deste n.º 3 e no artigo 30.º, n.º 2. O RSD não dá orientações sobre o modo de concretização deste critério de diligência.

Trata-se de uma obrigação de verificação aleatória, atendendo a que o fornecedor não tem uma obrigação geral de vigilância[fn:45]. Por esse motivo, o fornecedor não deve verificar /todos/ os produtos ou serviços oferecidos na sua plataforma nem está obrigado a verificar /todos/ os produtos ou serviços oferecidos através de verificações aleatórias /parciais periódicas/[cite:@muller-terpitz2023, art. 31.º, n.º 22]. A redação não é clara, mas atendendo ao objetivo prosseguido por esta obrigação de verificação, considera-se que a mesma /não/ se cumpre com a realização de /uma/ verificação aleatória, mantendo-se a obrigação enquanto o comerciante ofereça na plataforma em linha produtos ou serviços aos consumidores localizados na União Europeia. Deste modo, a verificação é aleatória quanto aos produtos e serviços sobre que incide, mas deve ser realizada periodicamente[cite:@hofmann2023, art. 31.º, n.º 30;@muller-terpitz2023 31.º, n.º 22].

A verificação deve ser efetuada através da pesquisa em base de dados em linha ou interface em linha oficial, de acesso livre e legível por máquina, disponíveis num Estado-Membro ou na União. Em matéria de segurança dos produtos, o artigo 22.º, n.º 7, do Regulamento relativo à segurança geral dos produtos estabelece que os fornecederos devem utilizar, pelo menos, o portal do /Safety Gate/.

Se, após a verificação, o fornecedor determinar que um determinado produto ou serviço foi identificado como ilegal, é aplicável o artigo 6.º do RSD, para cuja anotação se remete[cite:@muller-terpitz2023, art. 31.º, n.º 24].


* Anotação artigo 32.º :ignore:
** Transcrição do artigo :ignore:

#+begin_quote
*Artigo 32.º (Direito à informação)*

1.   Caso um fornecedor de uma plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes tome conhecimento, independentemente do meio utilizado, de que um produto ou serviço ilegal foi oferecido por um comerciante a consumidores localizados na União através dos seus serviços, esse fornecedor deve, na medida em que disponha dos seus dados de contacto, informar os consumidores que adquiriram o produto ou serviço ilegais através dos seus serviços do seguinte:
   a) Do facto de o produto ou serviço ser ilegal;
   b) Da identidade do comerciante; e
   c) De quaisquer meios de reparação aplicáveis.

   A obrigação estabelecida no primeiro parágrafo está limitada às aquisições de produtos ou serviços ilegais efetuadas durante os seis meses que precedem o momento em que o fornecedor tomou conhecimento da ilegalidade.
2.   Se, no caso referido no n.º 1, o fornecedor da plataforma em linha que permite aos consumidores celebrar contratos à distância com comerciantes não dispuser dos dados de contacto de todos os consumidores em causa, esse fornecedor disponibiliza ao público e torna facilmente acessível na sua interface em linha as informações sobre o produto ou serviço ilegal, a identidade do comerciante e quaisquer meios de reparação aplicáveis.
#+end_quote

** Bibliografia :ignore:

*Bibliografia:* /vide/ a indicada na anotação ao artigo 30.º;

** Comentário
*** I - Antecedentes legislativos
A Proposta não previa obrigações de informação em caso de oferta, através de plataformas em linha, de produtos ou serviços ilegais. A obrigação de informação foi proposta, durante o processo legislativo, pela Comissão dos Assuntos Jurídicos, com a introdução de um novo artigo 22b[fn:46]. Este preceito previa, para além da obrigação de informação, uma obrigação de retirada do produto ou serviço ilegal da plataforma em linha e informação das autoridades, assim como a criação de uma base de dados interna com os conteúdos removidos e ou os destinatários suspensos, que não constam na versão final do RSD. O preceito estabelecia também a obrigação de informar os consumidores que adquiriram o produto ou serviço ilegal nos 12 meses anteriores à data em que o fornecedor tomou conhecimento da natureza ilegal de um produto ou serviço. Este prazo foi, na versão final, reduzido para 6 meses.

*** II - Teleologia da norma
A norma visa, primariamente, reforçar a proteção dos consumidores, atribuindo aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes um papel a desempenhar na tarefa de garantir legalidade dos produtos e serviços oferecidos na União Europeia[cite:Cf., em sentido semelhante, @wilman2024, art. 32.º, n.º 1;@hofmann2023, art. 32.º, n.ºs 1 e 3;@muller-terpitz2023, art. 32.º, n.º 2]. A norma também protege os comerciantes concorrentes e os titulares de direitos de propriedade intelectual[cite:@hofmann2023, art. 32.º, n.º 2] e pode, inclusive, ter um efeito disuasor na oferta de produtos e serviços ilegais atendendo aos (potencialmente muito elevados) danos reputacionais e patrimoniais que podem advir da informação aos consumidores ou divulgação ao público de que determinado comerciante ofereceu produtos ou serviços ilegais.

*** III - Âmbito de aplicação
*1. Âmbito de aplicação subjetivo*. O artigo 32.º é aplicável aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes que não beneficiem da isenção prevista no artigo 29.º. Na concretização dos destinatários da norma são relevantes os conceitos de "consumidor", "comerciante", "plataforma em linha", e "contrato à distância" definidos no artigo 3.º, e para o qual se remete. O conceito de "plataformas em linha que permitem aos consumidores celebrar contratos à distância" é muito próximo do conceito de "mercado em linha"[fn:19], mas não inclui as plataformas que apenas permitem a celebração de contratos entre consumidores[cite:@muller-terpitz2023, art. 32.º, n.º 4;@hofmann2023, art. 32.º, n.º 7;e, no contexto do artigo 30.º, transponível também para este preceito, cf. @wilman2024 p. 224, n.º 8].

*2. Âmbito de aplicação material*. As obrigações de informação e divulgação incidem sobre a oferta e aquisição pelo consumidor de produtos ou serviços ilegais através da plataforma em linha do fornecedor.

Os conceitos de "produto ilegal" e "serviço ilegal" não são definidos no RSD. O RSD define o conceito de "conteúdos ilegais" no artigo 3.º, alínea /h)/, para cuja anotação se remete. Traçando um paralelo com o conceito de conteúdos ilegais, dir-se-á que produtos ou serviços ilegais são os que não estejam em conformidade com o direito da União ou com o direito de qualquer um dos Estados-Membros que seja conforme com o direito da União, independentemente do objeto ou da natureza precisa desse direito[cite:@hofmann2023, art. 32.º, n.º 18;@muller-terpitz2023, art. 32.º, n.º 6]. As obrigações do artigo 32.º não incidem sobre conteúdos ilegais e, por isso, não são aplicávais se o produto não for ilegal, mesmo se as fotos colocadas na plataforma em linha para o promover constituírem conteúdo ilegal por violarem direitos de autor[cite:Exemplo retirado de @hofmann2023, art. 32.º, n.º 18].

O fornecedor só tem a obrigação de informar ou divulgar se os produtos ou serviços foram oferecidos e adquiridos por consumidores através da sua plataforma. Se o produto ou serviço ilegal foi oferecido ao consumidor ou adquirido por este por meio diverso da plataforma em linha, quebra-se a conexão decorrente da atual importância destes intermediários no comércio em linha que parece justificar a imposição destas obrigações adicionais[cite:@muller-terpitz2023, art. 32.º, n.º 8].

*3. Âmbito de aplicação espacial*. As obrigações de informação e divulgação impostas neste artigo aos fornecedores de plataformas em linha que permitem aos consumidores celebrar contratos à distância com comerciantes estão limitada em função do âmbito de aplicação espacial do RSD, definido no art. 2.º, para o qual se remete. Por isso, essas obrigações só são aplicáveis se o produto ou serviço ilegal foi oferecido na plataforma em linha por um comerciante a consumidores localizados na União Europeia. Assim, e por exemplo, o artigo 32.º não é aplicável nos casos em que um comerciante ofereça na plataforma em linha produtos que não cumpram a legislação europeia desde que limite a oferta desses produtos a pessoas localizadas fora da União Europeia.

*4. Âmbito de aplicação temporal*. As obrigações de informação e divulgação estão limitada às aquisições de produtos ou serviços ilegais efetuadas durante os seis meses que precedem o momento em que o fornecedor tomou conhecimento da ilegalidade (n.º 1, 2.º parágrafo). Assim, e por exemplo, o fornecedor não têm a obrigação de informar ou divulgar ao publico que um comerciante ofereceu determinado produto ou serviço ilegal aos consumidores localizados na União Europeia se, nos 6 meses anteriores à tomada de conhecimento da ilegalidade pelo fornecedor, nenhum consumidor localizado na União Europeia adquiriu o produto ou serviço.

A data da aquisição é a data em que foi celebrado o contrato entre o comerciante e o consumidor. A data da execução do contrato não é relevante. A data da celebração pode ser facilmente determinada pelo fornecedor, uma vez que o contrato foi celebrado através da sua plataforma em linha[cite:@hofmann2023, art. 32.º, n.º 29]. A determinação precisa da data em fornecedor tomou conhecimento da ilegalidade reveste maior complexidade e variabilidade, atendendo a que o conhecimento pode advir por qualquer meio (cf. /infra/ *IV.5.a).*).

*** IV - Obrigação de informar os consumidores que adquiriram o produto ou serviço ilegal (n.º 1)
*5. Pressupostos*. São dois os pressuspostos da obrigação de informação prevista no n.º 1: o fornecedor tem de tomar conhecimento de que foi oferecido um produto ou serviço ilegal através da sua plataforma em linha e tem de dispor dos dados de contacto dos consumidores localizados na União Europeia que adquiriram esse produto ou serviço ilegal.

*a) Conhecimento de que foi oferecido produto ou serviço ilegal*. O conhecimento é exigido, mas não é definido no RSD. Da redação do preceito, conjugada com a ausência de uma obrigação geral de vigilância (artigo 8.º do RSD), resulta que não é suficiente o forneceddor ter conhecimento, em sentido geral, de que o seu serviço é  utilizado para oferecer produtos ou serviços ilegais. O fornecedor tem de tomar conhecimento concreto de que /determinado/ produto ou serviço ilegal é oferecido na sua plataforma em linha[fn:47]. O conhecimento concreto abrange o /concreto/ produto ou serviço /e/ a sua natureza ilegal[cite:@hofmann2023, art. 32.º, n.º 12].

O meio utilizado para obter conhecimento é irrelevante. O conhecimento pode advir por qualquer meio, nomeadamente através de investigações realizadas por iniciativa própria, verificações efetuadas ao abrigo do artigo 31.º, n.º 3, do RSD ou notificações remetidas ao fornecedor. Quanto a estas últimas recorda-se a jurisprudência do TJ, proferida no contexto do artigo 14.º da DCE, de que "uma notificação não pode automaticamente retirar o direito à isenção de responsabilidade prevista no artigo 14.° da Directiva 2000/31, dado que as notificações de actividades ou informações alegadamente ilegais se podem revelar insuficientemente precisas e demonstradas"[fn:48].

No contexto do artigo 32.º, em que o cumprimento da obrigação de informação pode acarretar danos reputacionais muito elevados para o comerciante, considera-se que o fornecedor deve ser cuidadoso ao estabelecer o conhecimento da ilegalidade do produto ou serviço. Por exemplo, nos casos em que é alertado para a ilegalidade de determinado produto ou serviço por notificações de terceiros, o fornecedor deverá previamente dar uma oportunidade ao comerciante para se pronunciar[cite:@hofmann2023, art. 32.º, n.ºs 13 e ss.].

*b) Dados de contacto dos consumidores adquirentes do produto ou serviço ilegal*. O artigo 32.º estabelece que o fornecedor só tem a obrigação de informar os consumidor se dispuser dos seus dados de contacto, mas não o obriga a ter e tratar esses dados de contacto para este propósito[cite:@wilman2024 32.º, n.º 3, consideram que o estabelecimento de tal obrigação violaria o artigo 6.º, n.º 1 do RGPD]. O conceito de dados de contacto, embora não definido no RSD, abrange o endereço de correio eletrónico, o endereço postal e o número de telefone do consumidor[fn:49].

*6. Conteúdo*. O consumidor deve ser informado de que o produto ou serviço é ilegal (n.º 1, al. /a)/), da identidade do comerciante (n.º 1, al. /b)/) e de quaisquer meios de reparação aplicáveis (n.º 1, al. /c)/).

*a) O facto de o produto ou serviço ser ilegal*. Da redação da al. /a)/ não resulta o dever de informar os consumidor do motivo pelo qual o produto ou serviço é ilegal. Parece haver apenas o dever de comunicar que o produto ou serviço é ilegal[cite:@muller-terpitz2023, art. 32.º, n.º 11]. Alguns autores sustentam que o dever de indicar o fundamento da ilegalidade decorre, implicitamente, da obrigação de informar o consumidor de quaiquer meios de reparação aplicáveis[cite:@hofmann2023, art. 32.º, n.º 23].

*b) Identidade do comerciante*. O conceito de identidade não é definido no RSD. Alguns autores sustentam que o conceito de identidade, em regra, não abrangerá o endereço[cite:@hofmann2023, art. 32.º, n.º 25]. Outros reconduzem este conceito à informação que o fornecedor deve ter obtido do comerciante nos termos do art. 30.º, n.º 1, al. /a)/ do RSD[cite:@muller-terpitz2023, art. 32.º, n.º 11]. Este último entendimento parece preferível, atendendo ao objetivo de reforçar a proteção do consumidor e à relavância do endereço postal para o exercício judicial dos direitos do consumidor.

*c) Quaisquer meios de reparação aplicáveis*. As versões inglesa, francesa, italiana, espanhola e alemã do RSD indicam, respetivamente, que o consumidor deve ser informado de /"any relevant means of redress/, /"tout moyen de recours pertinent"/, /"di qualsiasi mezzo di ricorso pertinente"/, /"de cualquier vía de recurso pertinente"/ e /"die einschlägigen Rechtsbehelfe"/. A análise das várias versões linguísticas aponta no sentido de que não é suficiente uma comunicação, de caráter geral, ao consumidor sobre os seus direitos. Parece ser necessário uma adequação da informação a prestar às circunstâncias do caso concreto, pois o consumidor deve ser informado dos meios de reparação /pertinentes/. O RSD não dá indicações sobre esta matéria. Parece dever procurar-se um equilíbrio entre o encargo imposto aos fornecedores, que não deverá ser excessivo, e o objetivo de reforçar, atrvés da prestação desta informação, a proteção dos consumidores. Assim, não devem ser indicados todos os direitos do consumidor, pois os excesso de informação pode também dificultar o exercício dos seus direitos pelo consumidor, mas, por outro lado, o fornecedor não deverá ser onerado com a obrigação de efetuar uma delimitação precisa dos meios de reparação aplicáveis. Devem ser indicados os meios de reparação que, em princípio, podem ser aplicáveis ao caso concreto[cite:@hofmann2023, art. 32.º, n.º 26;@muller-terpitz2023, art. 32.º, n.º 12].

*7. Modos de prestação*. Não é definido como deve o fornecedor comunicar a informação aos consumidores. Regra geral, admite-se que a solução mais comum será o envio da informação através de mensagem para o endereço de correio eletrónico do consumidor. A informação pode também ser prestada mediante envio de carta para o endereço postal do consumidor. A prestação da informação ao consumidor mediante contacto telefónico não parece adequada, desde logo pela quantidade de informação a prestação, pelos maiores encargos que acarreta para o fornecedor[cite:@muller-terpitz2023, art. 32.º, n.º 13] e por não consubstanciar um registo duradouro que permita consultas repetidas pelo consumidor. Pparece, no entanto, possível - embora não tão comum como o envio de mensagens por correio eletrónico - o envio da informação através de aplicações de troca de mensagens que utilizem o contacto telefónico para identificar os seus utilizadores (/v.g. Whatsapp/).

Em contraponto, a prestação da informação através da própria plataforma em linha - mesmo quando esta tenha um sistema interno de troca de mensagens - não parece poder incluir-se no conceito de dados de contacto, pois normalmente pressupõe que o consumidor tem de aceder à plataforma em linha para verificar as mensagens[cite:Cf., em sentido semelhante, @muller-terpitz2023, art. 32.º, n.º 13].

*** V - Obrigação de divulgação (n.º 2)

*8. Pressupostos*. Para que o fornecedor tenha a obrigação de divulgação é necessário que tome conhecimento de um produto ou serviço ilegal foi oferecido por um comerciante a consumidores localizados na União Europeia através da sua plataforma em linha, adquirido por estes durante os seis meses que precederam o momento em que tomou conhecimento da ilegalidade, e que não disponha dos dados de contacto de todos os consumidores em causa. Em suma, a obrigação de divulgação (n.º 2) é aplicável nos casos em que, por qualquer motivo, o fornecedor não dispõe dos dados de contacto de /todos/ os consumidores localizados na União Europeia que, naquele prazo de 6 meses, adquiriram o produto ou serviço ilegal.

A obrigação de divulgação (n.º 2) substitui a obrigação de informação (n.º 1), nos casos em que o fornecedor não disponha dos dados de contacto de nenhum dos consumidores adquirentes. Pode, no entanto, questionar-se se o mesmo sucede nos casos em que o fornecedor dispõe dos dados de contacto de alguns, mas não de todos os consumidores adquirentes. Ou se, neste caso, o fornecedor está obrigado a informar diretamente os consumidores adquirente cujos meios de contacto dispõe (n.º 1) e a cumprir a obrigação de divulgação (n.º 2), pois não tem possibilidade de informar diretamente os restantes consumidores adquirentes. Atendendo ao objetivo de proteção do consumidores, e ao facto de a obrigação de divulgação não garantir o conhecimento por parte dos consumidores adquirentes (uma vez que estes têm de se dirigir à plataforma em linha para consultarem a informação), entende-se que, nos casos em que o forneceder só disponha dos dados de contacto de parte dos consumidores adquirentes, ele deve cumprir a obrigação de informação quanto a estes e também a obrigação de divulgação constante do n.º 2.

*9. Conteúdo*. A obrigação de divulgação abrange as informações sobre o produto ou serviço ilegal, a identidade do comerciante e quaisquer meios de reparação aplicáveis. A expressão "informações sobre o produto ou serviço ilegal" parece ser mais abrangente do que a prevista no n.º 1, al. /a)/. Tal pode compreender-se porque, neste caso, o fornecedor não pode contactar diretamente todos os consumidores que adquiriram o produto ou serviço ilegal e, por isso, deve divulgar informações que permitam aos consumidores identificar inequivocamente se adquiriram ou não aquele produto ou serviço ilegal. Assim, inclui-se, por exemplo, a designação, modelo, n.º de série, descrição e imagens do produto ilegal[cite:@muller-terpitz2023, art. 32.º, n.º 16]. As informações relativas à identidade do comerciante e aos meios de reparação correspondem às previstas no n.º 1, als. /b)/ e /c)/ (cf. /supra/ *IV.5.b) e c)*).

*10. Modo de divulgação*. A informação tem de ser disponibilizada ao público, de modo facilmente acessível, na interface em linha da plataforma em linha do fornecedor. O requisito de disponibilização ao público é preenchido desde que a informação seja colocada em local da plataforma em linha que possa ser acedido por qualquer internauta, mesmo que não tenha conta na plataforma em linha (ou não acedido a esta)[cite:@hofmann2023, art. 32.º, n.º 32;@muller-terpitz2023, art. 32.º, n.º 18]. As informações são facilmente acessíveis se o público consegue aceder à informação sem necessitar de pesquisar muito por ela[cite:@muller-terpitz2023, art. 32.º, n.º 19], não devendo a interface em linha constituir um entrave ao acesso à informação[cite:Cf., no contexto do artigo 14.º, @knapp2024, p. 113]. Um modo de o alcançar será, por exemplo, criar uma secção específica na interface em linha da plataforma em linha, acessível desde logo na página de entrada da plataforma, para a divulgação destas informações[cite:@hofmann2023, art. 32.º, n.º 32].


* Footnotes
[fn:49] Cf. o artigo 30.º, n.º 1, al. /a)/, do RSD, no que se refere aos dados que o fornecedor tem de obter dos comerciantes que utilizam a sua plataforma em linha.

[fn:48] Cf. Acórdão do TJ de 12 de julho de 2011, /L'Oréal e o./, proc. C-324/09, EU:C:2011:474, n.º 122.

[fn:47] Cf., no contexto do artigo 6.º do RSD, o considerando n.º 22 e, no contexto do artigo 14.º da DCE, o Acórdão do TJ de 22 de junho de 2021, /YouTube e Cyando/, processos apensos C-682/18 e C-683/18, EU:C:2021:503, n.ºs 113 e 114.

[fn:46] Cf. Relatório sobre a proposta de Regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE, de 20.12.2021, (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)), alteração 246, p. 514.

[fn:45] Cf. artigo 8.º do RSD e considerando n.º 74.

[fn:44] Cf. considerando n.º 74.

[fn:43] Cf. Regulamento (CE) n.º 1272/2008 do Parlamento Europeu e do Conselho, de 16 de Dezembro de 2008, relativo à classificação, rotulagem e embalagem de substâncias e misturas, que altera e revoga as Directivas 67/548/CEE e 1999/45/CE, e altera o Regulamento (CE) n.º 1907/2006, publicado em JO L 353 de 31.12.2008.

[fn:42] Cf. artigo 3.º, ponto 13, do Regulamento (UE) 2019/1020 do Parlamento Europeu e do Conselho, de 20 de junho de 2019, relativo à fiscalização do mercado e à conformidade dos produtos e que altera a Diretiva 2004/42/CE e os Regulamentos (CE) n.º 765/2008 e (UE) n.º 305/2011, publicado no JO L 169 de 25.6.2019.

[fn:41] Cf., respetivamente, artigos 19.º e 20.º do Regulamento relativo aos dispositivos médicos.

[fn:40] Regulamento (UE) 2017/745 do Parlamento Europeu e do Conselho, de 5 de abril de 2017, relativo aos dispositivos médicos, que altera a Diretiva 2001/83/CE, o Regulamento (CE) n.° 178/2002 e o Regulamento (CE) n.° 1223/2009 e que revoga as Diretivas 90/385/CEE e 93/42/CEE do Conselho, publicado no JO L 117 de 5.5.2017.

[fn:39] Exemplos retirados do considerando n.º 74.

[fn:38] Diretiva 98/6/CE do Parlamento Europeu e do Conselho, de 16 de fevereiro de 1998, relativa à defesa dos consumidores em matéria de indicações dos preços dos produtos oferecidos aos consumidores, publicada no JO L 80 de 18.3.1998.

[fn:37] Diretiva 2005/29/CE do Parlamento Europeu e do Conselho, de 11 de maio de 2005, relativa às práticas comerciais desleais das empresas face aos consumidores no mercado interno e que altera a Diretiva 84/450/CEE do Conselho, as Diretivas 97/7/CE, 98/27/CE e 2002/65/CE e o Regulamento (CE) n.º 2006/2004, publicada no JO L 149 de 11.6.2005.

[fn:36] Cf. Relatório sobre a proposta de Regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE, de 20.12.2021, (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)), alteração 245, p. 513.

[fn:35] Cf. Considerando n.º 72.

[fn:34] Art. 22.º, n.º 4, da Proposta.

[fn:33] Cf. Considerando n.º 72.

[fn:32] Regulamento (UE) 2019/1150 do Parlamento Europeu e do Conselho, de 20 de junho de 2019, relativo à promoção da equidade e da transparência para os utilizadores profissionais de serviços de intermediação em linha, publicado no JO L 186 de 11.7.2019.

[fn:31] Comunicação da Comissão ao Parlamento Europeu e ao Conselho : Orientações sobre o artigo 17.º da Diretiva 2019/790 relativa aos direitos de autor no
mercado único digital, COM(2021) 288 final, 4.6.2021, pp. 9 e ss.

[fn:30] Cf. considerando n.º 73.

[fn:29] Cf. considerando n.º 73.

[fn:28] Cf. considerando n.º 73.

[fn:27] Regulamento (UE) 2015/751 do Parlamento Europeu e do Conselho, de 29 de abril de 2015, relativo às taxas de intercâmbio aplicáveis a operações de pagamento baseadas em cartões, publicado no JO L 123 de 19.5.2015.

[fn:26] "«Conta de pagamento», uma conta detida em nome de um ou mais utilizadores de serviços de pagamento, utilizada para a execução de operações de pagamento, inclusive através de uma conta específica para moeda eletrónica, na aceção do artigo 2.º, ponto 2, da Diretiva 2009/110/CE do Parlamento Europeu e do Conselho".

[fn:25] Regulamento (UE) n. ° 910/2014 do Parlamento Europeu e do Conselho, de 23 de julho de 2014 , relativo à identificação eletrónica e aos serviços de confiança para as transações eletrónicas no mercado interno e que revoga a Diretiva 1999/93/CE, publicado no JO L 257 de 28.8.2014.

[fn:24] Cf. Acórdão de 10 de julho de 2019, /Amazon EU/, C-649/17, EU:C:2019:576, considerando n.º 51.

[fn:23] Regulamento (UE) n. ° 1215/2012 do Parlamento Europeu e do Conselho, de 12 de dezembro de 2012, relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercial (reformulação), publicado no JO L 351 de 20.12.2012.

[fn:22] Directiva 2011/83/UE do Parlamento Europeu e do Conselho, de 25 de Outubro de 2011, relativa aos direitos dos consumidores, que altera a Directiva 93/13/CEE do Conselho e a Directiva 1999/44/CE do Parlamento Europeu e do Conselho e que revoga a Directiva 85/577/CEE do Conselho e a Directiva 97/7/CE do Parlamento Europeu e do Conselho Texto relevante para efeitos do EEE, publicada no JO L 304 de 22.11.2011.

[fn:21] Directiva 2006/123/CE do Parlamento Europeu e do Conselho, de 12 de Dezembro de 2006 , relativa aos serviços no mercado interno, publicada no JO L 376 de 27.12.2006.

[fn:20] Diretiva (UE) 2019/771 do Parlamento Europeu e do Conselho, de 20 de maio de 2019, relativa a certos aspetos dos contratos de compra e venda de bens que altera o Regulamento (UE) 2017/2394 e a Diretiva 2009/22/CE e que revoga a Diretiva 1999/44/CE, publicada no JO L 136 de 22.5.2019.

[fn:19] Introduzido pela Diretiva (UE) 2019/2161 do Parlamento Europeu e do Conselho de 27 de novembro de 2019 que altera a Diretiva 93/13/CEE do Conselho e as Diretivas 98/6/CE, 2005/29/CE e 2011/83/UE do Parlamento Europeu e do Conselho a fim de assegurar uma melhor aplicação e a modernização das regras da União em matéria de defesa dos consumidores, publicada no JO L 328 de 18 de dezembro de 2019.

[fn:18] Considerando n.º 72.

[fn:17] Considerando n.º 72.

[fn:15] Cf. artigo 4.º, n.º 2, do Anexo da Recomendação 2003/361/CE.

[fn:14] Cf. Acórdãos de 27 de fevereiro de 2014, /HaTeFo/, C-110/13, EU:C:2014:114, considerando n.º 32, de 24 de setembro de 2020, /NMI Technologietransfer/, C-516/19, EU:C:2020:754, considerando n.º 65, e de 10 de março de 2021, /Ertico - ITS Europe contra Comissão Europeia/, C-572/19 P, EU:C:2021:188, considerando n.º 89.

[fn:13] Cf. artigos 4.º, 5.º e 6.º do Anexo da Recomendação 2003/361/CE.

[fn:12] Cf. artigo 3.º, n.º 4, do Anexo da Recomendação 2003/261/CE.

[fn:11] Cf. artigo 3.º do Anexo da Recomendação 2003/261/CE.

[fn:10] Cf. artigo 1.º do Anexo da Recomendação 2003/261/CE.

[fn:9] Cf. artigo 2.º, n.º 2, do Anexo da Recomendação 2003/361/CE.

[fn:8] Cf. artigo 2.º, n.º 3, do Anexo da Recomendação 2003/361/CE.

[fn:7] Recomendação da Comissão, de 6 de Maio de 2003, relativa à definição de micro, pequenas e médias empresas, notificada com o número C(2003) 1422, publicada no JO L 124, de 20 de maio de 2003.

[fn:6] Cf. artigo 22.º do Regulamento (UE) 2023/988 do Parlamento Europeu e do Conselho de 10 de maio de 2023 relativo à segurança geral dos produtos, que altera o Regulamento (UE) n.o 1025/2012 do Parlamento Europeu e do Conselho e a Diretiva (UE) 2020/1828 do Parlamento Europeu e do Conselho e que revoga a Diretiva 2001/95/CE do Parlamento Europeu e do Conselho e a Diretiva 87/357/CEE do Conselho, publicado no JO L 135, de 23 de maio de 2023.

[fn:5] Cf., neste sentido, Parecer do Comité Económico e Social Europeu sobre a «Proposta de regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE», publicado no JO C 286, de 16 de julho de 2021, ponto 3.7.

[fn:4] Cf. considerando n.º 57.

[fn:3] cf. RETIFICAÇÃO da posição do Parlamento Europeu aprovada em primeira leitura, em 5 de julho de 2022, tendo em vista a adoção do Regulamento (UE) 2022/... do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE, doc. P9_TA(2022)0269 de 8 de setembro de 2022 (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)), disponível em https://www.europarl.europa.eu/doceo/document/TA-9-2022-0269_PT.html e consultada pela última vez em 20 de fevereiro de 2025.

[fn:2] Cf. o /Provisional Agreement resulting from Interinstitutional Negotiations/, de 15 de junho de 2022, doc. PE734.11, disponível em https://oeil.secure.europarl.europa.eu/oeil/en/procedure-file?reference=2020/0361(COD) e consultado pela última vez em 20 de fevereiro de 2025.

[fn:1] Cf., respetivamente, o Projeto de Relatório sobre a proposta de Regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)) - relatora: Christel Schaldemose, as alterações aprovadas, em primeira leitura, pelo Parlamento Europeu, em 20 de janeiro de 2022, sobre a proposta de regulamento do Parlamento Europeu e do Conselho relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE (COM(2020)0825 – C9-0418/2020 – 2020/0361(COD)), disponíveis em https://oeil.secure.europarl.europa.eu/oeil/en/procedure-file?reference=2020/0361(COD) e consultados pela última vez em 20 de fevereiro de 2025, e a Proposta de REGULAMENTO DO PARLAMENTO EUROPEU E DO CONSELHO relativo a um mercado único de serviços digitais (Regulamento Serviços Digitais) e que altera a Diretiva 2000/31/CE - Orientação geral, de 18 de novembro de 2021, doc. 13203/21, disponível em https://eur-lex.europa.eu/legal-content/PT/HIS/?uri=CELEX:32022R2065&qid=1739909682588 e consultado pela última vez em 20 de fevereiro de 2025.
